# Generated by ariadne-codegen

from .base_operation import GraphQLField


class AccelzoneLowerBoundsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AccelzoneLowerBoundsGraphQLField":
        self._alias = alias
        return self


class AccelzonesPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AccelzonesPayloadGraphQLField":
        self._alias = alias
        return self


class AcceptPrivacyPolicyPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AcceptPrivacyPolicyPayloadGraphQLField":
        self._alias = alias
        return self


class AddAthleteGroupPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AddAthleteGroupPayloadGraphQLField":
        self._alias = alias
        return self


class AddExistingPersonToClubPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AddExistingPersonToClubPayloadGraphQLField":
        self._alias = alias
        return self


class AddNewPersonToClubPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AddNewPersonToClubPayloadGraphQLField":
        self._alias = alias
        return self


class AddSurveyAnswerPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AddSurveyAnswerPayloadGraphQLField":
        self._alias = alias
        return self


class AddSurveyQuestionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AddSurveyQuestionPayloadGraphQLField":
        self._alias = alias
        return self


class AggregateInterfaceGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AggregateInterfaceGraphQLField":
        self._alias = alias
        return self


class AggregatedSessionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AggregatedSessionGraphQLField":
        self._alias = alias
        return self


class AggregatedSessionMetricSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AggregatedSessionMetricSetGraphQLField":
        self._alias = alias
        return self


class AnchorGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AnchorGraphQLField":
        self._alias = alias
        return self


class AppMessageGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AppMessageGraphQLField":
        self._alias = alias
        return self


class AppMessageContextUnion(GraphQLField):
    def on(self, type_name: str, *subfields: GraphQLField) -> "AppMessageContextUnion":
        self._inline_fragments[type_name] = subfields
        return self

    def alias(self, alias: str) -> "AppMessageContextUnion":
        self._alias = alias
        return self


class ArchiveClubMemberPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ArchiveClubMemberPayloadGraphQLField":
        self._alias = alias
        return self


class ArchivePitchPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ArchivePitchPayloadGraphQLField":
        self._alias = alias
        return self


class ArchiveSurveyPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ArchiveSurveyPayloadGraphQLField":
        self._alias = alias
        return self


class AssignDevicePayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AssignDevicePayloadGraphQLField":
        self._alias = alias
        return self


class AssignEdgePayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AssignEdgePayloadGraphQLField":
        self._alias = alias
        return self


class AthleteGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteGraphQLField":
        self._alias = alias
        return self


class AthleteGroupGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteGroupGraphQLField":
        self._alias = alias
        return self


class AthleteLabelledAccelzonesGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteLabelledAccelzonesGraphQLField":
        self._alias = alias
        return self


class AthleteLabelledDecelzonesGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteLabelledDecelzonesGraphQLField":
        self._alias = alias
        return self


class AthleteLabelledHeartRateBoundsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteLabelledHeartRateBoundsGraphQLField":
        self._alias = alias
        return self


class AthleteLabelledSpeedzonesGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteLabelledSpeedzonesGraphQLField":
        self._alias = alias
        return self


class AthleteMetricsSummaryGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteMetricsSummaryGraphQLField":
        self._alias = alias
        return self


class AthleteOrStaffGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteOrStaffGraphQLField":
        self._alias = alias
        return self


class AthletePeriodMetricsUpdatedSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "AthletePeriodMetricsUpdatedSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class AthleteRecordsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteRecordsGraphQLField":
        self._alias = alias
        return self


class AthleteSegmentMetricsUpdatedSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "AthleteSegmentMetricsUpdatedSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class AthleteSessionLinkGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteSessionLinkGraphQLField":
        self._alias = alias
        return self


class AthleteSessionMetricsUpdatedSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "AthleteSessionMetricsUpdatedSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class AthleteStaffOrPdStaffGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AthleteStaffOrPdStaffGraphQLField":
        self._alias = alias
        return self


class AveragePositionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AveragePositionGraphQLField":
        self._alias = alias
        return self


class BallGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "BallGraphQLField":
        self._alias = alias
        return self


class BallDataRecordingGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "BallDataRecordingGraphQLField":
        self._alias = alias
        return self


class BucketGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "BucketGraphQLField":
        self._alias = alias
        return self


class BulkApprovePayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "BulkApprovePayloadGraphQLField":
        self._alias = alias
        return self


class CameraOwnershipGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CameraOwnershipGraphQLField":
        self._alias = alias
        return self


class CellRangeGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CellRangeGraphQLField":
        self._alias = alias
        return self


class ChargebeeSubscriptionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ChargebeeSubscriptionGraphQLField":
        self._alias = alias
        return self


class ChartConfigGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ChartConfigGraphQLField":
        self._alias = alias
        return self


class ClaimPersonPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ClaimPersonPayloadGraphQLField":
        self._alias = alias
        return self


class ClippedTimePeriodGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ClippedTimePeriodGraphQLField":
        self._alias = alias
        return self


class ClippedTimePeriodByAthleteGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ClippedTimePeriodByAthleteGraphQLField":
        self._alias = alias
        return self


class ClubGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ClubGraphQLField":
        self._alias = alias
        return self


class ClubContextGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ClubContextGraphQLField":
        self._alias = alias
        return self


class ClubMutationGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ClubMutationGraphQLField":
        self._alias = alias
        return self


class ClubSessionsSummaryMetricsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ClubSessionsSummaryMetricsGraphQLField":
        self._alias = alias
        return self


class ClubWeekOverviewGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ClubWeekOverviewGraphQLField":
        self._alias = alias
        return self


class CoachContextGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CoachContextGraphQLField":
        self._alias = alias
        return self


class CommonAggregatedMetricsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CommonAggregatedMetricsGraphQLField":
        self._alias = alias
        return self


class CommonAthleteMetricsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CommonAthleteMetricsGraphQLField":
        self._alias = alias
        return self


class ConfigurableAthleteSummaryGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ConfigurableAthleteSummaryGraphQLField":
        self._alias = alias
        return self


class ConfiguredAggMetricsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ConfiguredAggMetricsGraphQLField":
        self._alias = alias
        return self


class ConfiguredMetricsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ConfiguredMetricsGraphQLField":
        self._alias = alias
        return self


class ConfiguredPersonalBestsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ConfiguredPersonalBestsGraphQLField":
        self._alias = alias
        return self


class CreateCustomQuestionDefinitionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateCustomQuestionDefinitionPayloadGraphQLField":
        self._alias = alias
        return self


class CreateDatasetPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateDatasetPayloadGraphQLField":
        self._alias = alias
        return self


class CreateDeviceSyncPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateDeviceSyncPayloadGraphQLField":
        self._alias = alias
        return self


class CreateEdgeNamePayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateEdgeNamePayloadGraphQLField":
        self._alias = alias
        return self


class CreateFlexibleReportChartPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateFlexibleReportChartPayloadGraphQLField":
        self._alias = alias
        return self


class CreateFlexibleReportPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateFlexibleReportPayloadGraphQLField":
        self._alias = alias
        return self


class CreateMatchEventPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateMatchEventPayloadGraphQLField":
        self._alias = alias
        return self


class CreateMatchEventsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateMatchEventsPayloadGraphQLField":
        self._alias = alias
        return self


class CreatePitchPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreatePitchPayloadGraphQLField":
        self._alias = alias
        return self


class CreateQuestionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateQuestionPayloadGraphQLField":
        self._alias = alias
        return self


class CreateReportPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateReportPayloadGraphQLField":
        self._alias = alias
        return self


class CreateResponsePayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateResponsePayloadGraphQLField":
        self._alias = alias
        return self


class CreateSegmentPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateSegmentPayloadGraphQLField":
        self._alias = alias
        return self


class CreateSessionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateSessionPayloadGraphQLField":
        self._alias = alias
        return self


class CreateSessionTagDefinitionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateSessionTagDefinitionPayloadGraphQLField":
        self._alias = alias
        return self


class CreateSurveyDistributionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateSurveyDistributionPayloadGraphQLField":
        self._alias = alias
        return self


class CreateSurveyPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateSurveyPayloadGraphQLField":
        self._alias = alias
        return self


class CreateSurveyTimerTriggerPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateSurveyTimerTriggerPayloadGraphQLField":
        self._alias = alias
        return self


class CreateTagDefinitionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateTagDefinitionPayloadGraphQLField":
        self._alias = alias
        return self


class CreateVideoRecordingPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CreateVideoRecordingPayloadGraphQLField":
        self._alias = alias
        return self


class CryptoCharacteristicMismatchGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CryptoCharacteristicMismatchGraphQLField":
        self._alias = alias
        return self


class CryptoNonceMismatchGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CryptoNonceMismatchGraphQLField":
        self._alias = alias
        return self


class CryptoSignatureErrorGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CryptoSignatureErrorGraphQLField":
        self._alias = alias
        return self


class CustomQuestionDefinitionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CustomQuestionDefinitionGraphQLField":
        self._alias = alias
        return self


class CustomerSubscriptionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CustomerSubscriptionGraphQLField":
        self._alias = alias
        return self


class DataColumnGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataColumnGraphQLField":
        self._alias = alias
        return self


class DataReadyContextGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataReadyContextGraphQLField":
        self._alias = alias
        return self


class DataRecordingGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataRecordingGraphQLField":
        self._alias = alias
        return self


class DatasetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatasetGraphQLField":
        self._alias = alias
        return self


class DatasetTemplateGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatasetTemplateGraphQLField":
        self._alias = alias
        return self


class DayBreakdownOverviewGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DayBreakdownOverviewGraphQLField":
        self._alias = alias
        return self


class DecelzoneLowerBoundsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DecelzoneLowerBoundsGraphQLField":
        self._alias = alias
        return self


class DecelzonesPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DecelzonesPayloadGraphQLField":
        self._alias = alias
        return self


class DeleteAccelzonesPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DeleteAccelzonesPayloadGraphQLField":
        self._alias = alias
        return self


class DeleteDecelzonesPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DeleteDecelzonesPayloadGraphQLField":
        self._alias = alias
        return self


class DeleteHeartRateBoundsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DeleteHeartRateBoundsPayloadGraphQLField":
        self._alias = alias
        return self


class DeleteSpeedzonesPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DeleteSpeedzonesPayloadGraphQLField":
        self._alias = alias
        return self


class DestroyAppMessagePayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroyAppMessagePayloadGraphQLField":
        self._alias = alias
        return self


class DestroyAthleteGroupPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroyAthleteGroupPayloadGraphQLField":
        self._alias = alias
        return self


class DestroyCustomQuestionDefinitionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroyCustomQuestionDefinitionPayloadGraphQLField":
        self._alias = alias
        return self


class DestroyDatasetPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroyDatasetPayloadGraphQLField":
        self._alias = alias
        return self


class DestroyFlexibleReportChartsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroyFlexibleReportChartsPayloadGraphQLField":
        self._alias = alias
        return self


class DestroyFlexibleReportsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroyFlexibleReportsPayloadGraphQLField":
        self._alias = alias
        return self


class DestroyMatchEventPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroyMatchEventPayloadGraphQLField":
        self._alias = alias
        return self


class DestroyMatchEventsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroyMatchEventsPayloadGraphQLField":
        self._alias = alias
        return self


class DestroySegmentPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroySegmentPayloadGraphQLField":
        self._alias = alias
        return self


class DestroySessionBlueprintPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroySessionBlueprintPayloadGraphQLField":
        self._alias = alias
        return self


class DestroySessionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroySessionPayloadGraphQLField":
        self._alias = alias
        return self


class DestroySessionTagDefinitionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroySessionTagDefinitionPayloadGraphQLField":
        self._alias = alias
        return self


class DestroySurveyPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroySurveyPayloadGraphQLField":
        self._alias = alias
        return self


class DestroyTagDefinitionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DestroyTagDefinitionPayloadGraphQLField":
        self._alias = alias
        return self


class DetectedCoordinateGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DetectedCoordinateGraphQLField":
        self._alias = alias
        return self


class DetectedMatchEventGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DetectedMatchEventGraphQLField":
        self._alias = alias
        return self


class DetectedSessionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DetectedSessionGraphQLField":
        self._alias = alias
        return self


class DeviceInterfaceGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DeviceInterfaceGraphQLField":
        self._alias = alias
        return self


class DeviceOwnerUnion(GraphQLField):
    def on(self, type_name: str, *subfields: GraphQLField) -> "DeviceOwnerUnion":
        self._inline_fragments[type_name] = subfields
        return self

    def alias(self, alias: str) -> "DeviceOwnerUnion":
        self._alias = alias
        return self


class DeviceSyncGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DeviceSyncGraphQLField":
        self._alias = alias
        return self


class DiagnosticWarningGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DiagnosticWarningGraphQLField":
        self._alias = alias
        return self


class DuplicateFlexibleReportPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DuplicateFlexibleReportPayloadGraphQLField":
        self._alias = alias
        return self


class DuplicateSegmentPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DuplicateSegmentPayloadGraphQLField":
        self._alias = alias
        return self


class DuplicateSessionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DuplicateSessionPayloadGraphQLField":
        self._alias = alias
        return self


class DuplicateSurveyPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DuplicateSurveyPayloadGraphQLField":
        self._alias = alias
        return self


class EdgeGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "EdgeGraphQLField":
        self._alias = alias
        return self


class EdgeDataFileGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "EdgeDataFileGraphQLField":
        self._alias = alias
        return self


class EdgeDiagnosticInformationGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "EdgeDiagnosticInformationGraphQLField":
        self._alias = alias
        return self


class EdgeMetaEventGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "EdgeMetaEventGraphQLField":
        self._alias = alias
        return self


class EdgeNameGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "EdgeNameGraphQLField":
        self._alias = alias
        return self


class EndEdgeOwnershipPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "EndEdgeOwnershipPayloadGraphQLField":
        self._alias = alias
        return self


class ExamplePromptGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ExamplePromptGraphQLField":
        self._alias = alias
        return self


class FeatureCheckGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FeatureCheckGraphQLField":
        self._alias = alias
        return self


class FirmwareVersionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FirmwareVersionGraphQLField":
        self._alias = alias
        return self


class FlexibleReportGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlexibleReportGraphQLField":
        self._alias = alias
        return self


class FlexibleReportChartGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlexibleReportChartGraphQLField":
        self._alias = alias
        return self


class FloatMetricValueGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FloatMetricValueGraphQLField":
        self._alias = alias
        return self


class GatewayGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "GatewayGraphQLField":
        self._alias = alias
        return self


class GatewayOwnershipGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "GatewayOwnershipGraphQLField":
        self._alias = alias
        return self


class GatewaySessionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "GatewaySessionGraphQLField":
        self._alias = alias
        return self


class GenericMetricGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "GenericMetricGraphQLField":
        self._alias = alias
        return self


class GenericMetricExplanationGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "GenericMetricExplanationGraphQLField":
        self._alias = alias
        return self


class GenericPersonalBestsMetricGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "GenericPersonalBestsMetricGraphQLField":
        self._alias = alias
        return self


class HeartRateBoundsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "HeartRateBoundsPayloadGraphQLField":
        self._alias = alias
        return self


class HeartRateLowerBoundsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "HeartRateLowerBoundsGraphQLField":
        self._alias = alias
        return self


class HeartratePeripheralConnectedGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "HeartratePeripheralConnectedGraphQLField":
        self._alias = alias
        return self


class HeartratePeripheralDisconnectedGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "HeartratePeripheralDisconnectedGraphQLField":
        self._alias = alias
        return self


class IntMetricValueGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "IntMetricValueGraphQLField":
        self._alias = alias
        return self


class JsonMetricValueGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "JsonMetricValueGraphQLField":
        self._alias = alias
        return self


class LegacySurveyDistributedContextGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "LegacySurveyDistributedContextGraphQLField":
        self._alias = alias
        return self


class LinkUnion(GraphQLField):
    def on(self, type_name: str, *subfields: GraphQLField) -> "LinkUnion":
        self._inline_fragments[type_name] = subfields
        return self

    def alias(self, alias: str) -> "LinkUnion":
        self._alias = alias
        return self


class LocalizedTermsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "LocalizedTermsGraphQLField":
        self._alias = alias
        return self


class ManualSubscriptionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ManualSubscriptionGraphQLField":
        self._alias = alias
        return self


class MapCoordinateGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MapCoordinateGraphQLField":
        self._alias = alias
        return self


class MarkAppMessageReadPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MarkAppMessageReadPayloadGraphQLField":
        self._alias = alias
        return self


class MarkMultipleAppMessagesReadPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MarkMultipleAppMessagesReadPayloadGraphQLField":
        self._alias = alias
        return self


class MatchDefinitionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchDefinitionGraphQLField":
        self._alias = alias
        return self


class MatchEventGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchEventGraphQLField":
        self._alias = alias
        return self


class MatchEventCreatedSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchEventCreatedSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class MatchEventDefinitionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchEventDefinitionGraphQLField":
        self._alias = alias
        return self


class MatchFeatureGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchFeatureGraphQLField":
        self._alias = alias
        return self


class MatchSessionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchSessionGraphQLField":
        self._alias = alias
        return self


class MatchSessionAthleteMetricSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchSessionAthleteMetricSetGraphQLField":
        self._alias = alias
        return self


class MatchSessionAthletePeriodMetricSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchSessionAthletePeriodMetricSetGraphQLField":
        self._alias = alias
        return self


class MatchSessionLinkGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchSessionLinkGraphQLField":
        self._alias = alias
        return self


class MatchSessionMetricSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchSessionMetricSetGraphQLField":
        self._alias = alias
        return self


class MatchSessionParticipationGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchSessionParticipationGraphQLField":
        self._alias = alias
        return self


class MatchSessionParticipationPartGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchSessionParticipationPartGraphQLField":
        self._alias = alias
        return self


class MatchSessionParticipationPartMetricSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchSessionParticipationPartMetricSetGraphQLField":
        self._alias = alias
        return self


class MatchSessionPeriodGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchSessionPeriodGraphQLField":
        self._alias = alias
        return self


class MatchSessionPeriodMetricSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MatchSessionPeriodMetricSetGraphQLField":
        self._alias = alias
        return self


class MetricExplanationsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MetricExplanationsGraphQLField":
        self._alias = alias
        return self


class MetricSetAggMetadataGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MetricSetAggMetadataGraphQLField":
        self._alias = alias
        return self


class MetricSetMetadataGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MetricSetMetadataGraphQLField":
        self._alias = alias
        return self


class MetricValueUnionUnion(GraphQLField):
    def on(self, type_name: str, *subfields: GraphQLField) -> "MetricValueUnionUnion":
        self._inline_fragments[type_name] = subfields
        return self

    def alias(self, alias: str) -> "MetricValueUnionUnion":
        self._alias = alias
        return self


class MobileDeviceGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MobileDeviceGraphQLField":
        self._alias = alias
        return self


class NewPersonalBestContextGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "NewPersonalBestContextGraphQLField":
        self._alias = alias
        return self


class OperatingModeRequestGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "OperatingModeRequestGraphQLField":
        self._alias = alias
        return self


class OperatingModeTransitionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "OperatingModeTransitionGraphQLField":
        self._alias = alias
        return self


class OrganisationGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "OrganisationGraphQLField":
        self._alias = alias
        return self


class ParticipationsMetricsSummaryGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ParticipationsMetricsSummaryGraphQLField":
        self._alias = alias
        return self


class PathmapGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PathmapGraphQLField":
        self._alias = alias
        return self


class PathmapPitchLimitsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PathmapPitchLimitsGraphQLField":
        self._alias = alias
        return self


class PendingMemberGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PendingMemberGraphQLField":
        self._alias = alias
        return self


class PendingMemberCreatedSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "PendingMemberCreatedSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class PeriodGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PeriodGraphQLField":
        self._alias = alias
        return self


class PeriodMetricsUpdatedSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "PeriodMetricsUpdatedSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class PermissionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PermissionGraphQLField":
        self._alias = alias
        return self


class PersonGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PersonGraphQLField":
        self._alias = alias
        return self


class PersonSessionsSummaryMetricsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PersonSessionsSummaryMetricsGraphQLField":
        self._alias = alias
        return self


class PersonWeekOverviewGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PersonWeekOverviewGraphQLField":
        self._alias = alias
        return self


class PersonalBestsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PersonalBestsGraphQLField":
        self._alias = alias
        return self


class PitchGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PitchGraphQLField":
        self._alias = alias
        return self


class PitchCoordinateGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PitchCoordinateGraphQLField":
        self._alias = alias
        return self


class PitchCoordinateSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PitchCoordinateSetGraphQLField":
        self._alias = alias
        return self


class PitchCornersGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PitchCornersGraphQLField":
        self._alias = alias
        return self


class PitchDefinitionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PitchDefinitionGraphQLField":
        self._alias = alias
        return self


class PitchDetectedSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PitchDetectedSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class PositionDefinitionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PositionDefinitionGraphQLField":
        self._alias = alias
        return self


class PrivacyPolicyGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PrivacyPolicyGraphQLField":
        self._alias = alias
        return self


class PrivacyPolicyAcceptanceGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PrivacyPolicyAcceptanceGraphQLField":
        self._alias = alias
        return self


class ProfilePictureGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ProfilePictureGraphQLField":
        self._alias = alias
        return self


class ProvisionGatewayPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ProvisionGatewayPayloadGraphQLField":
        self._alias = alias
        return self


class QuestionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "QuestionGraphQLField":
        self._alias = alias
        return self


class QuestionSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "QuestionSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class RangeGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RangeGraphQLField":
        self._alias = alias
        return self


class RateResponsePayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RateResponsePayloadGraphQLField":
        self._alias = alias
        return self


class RecreateGatewaySessionsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RecreateGatewaySessionsPayloadGraphQLField":
        self._alias = alias
        return self


class RecurrenceScheduleGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RecurrenceScheduleGraphQLField":
        self._alias = alias
        return self


class RecurrenceScheduleWeeklyRuleGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RecurrenceScheduleWeeklyRuleGraphQLField":
        self._alias = alias
        return self


class RegisterDevicePayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RegisterDevicePayloadGraphQLField":
        self._alias = alias
        return self


class RelativeAccelzonesPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RelativeAccelzonesPayloadGraphQLField":
        self._alias = alias
        return self


class RelativeDecelzonesPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RelativeDecelzonesPayloadGraphQLField":
        self._alias = alias
        return self


class RelativeSpeedzonesPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RelativeSpeedzonesPayloadGraphQLField":
        self._alias = alias
        return self


class RemoveSurveyQuestionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RemoveSurveyQuestionPayloadGraphQLField":
        self._alias = alias
        return self


class RemoveSurveyTimerTriggerPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RemoveSurveyTimerTriggerPayloadGraphQLField":
        self._alias = alias
        return self


class ReportGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ReportGraphQLField":
        self._alias = alias
        return self


class ResendConfirmationEmailPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ResendConfirmationEmailPayloadGraphQLField":
        self._alias = alias
        return self


class ResendReportPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ResendReportPayloadGraphQLField":
        self._alias = alias
        return self


class RespondToDetectedMatchEventPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RespondToDetectedMatchEventPayloadGraphQLField":
        self._alias = alias
        return self


class RespondToDetectedMatchEventsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RespondToDetectedMatchEventsPayloadGraphQLField":
        self._alias = alias
        return self


class ResponseGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ResponseGraphQLField":
        self._alias = alias
        return self


class ReviewPendingMemberPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ReviewPendingMemberPayloadGraphQLField":
        self._alias = alias
        return self


class RootSubscriptionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RootSubscriptionGraphQLField":
        self._alias = alias
        return self


class RotateLiveDataKeysPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "RotateLiveDataKeysPayloadGraphQLField":
        self._alias = alias
        return self


class SegmentGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SegmentGraphQLField":
        self._alias = alias
        return self


class SegmentMetricsUpdatedSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "SegmentMetricsUpdatedSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class SegmentParticipationGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SegmentParticipationGraphQLField":
        self._alias = alias
        return self


class SegmentTitleGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SegmentTitleGraphQLField":
        self._alias = alias
        return self


class SeriesChartTypeGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SeriesChartTypeGraphQLField":
        self._alias = alias
        return self


class SessionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionGraphQLField":
        self._alias = alias
        return self


class SessionBlueprintGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionBlueprintGraphQLField":
        self._alias = alias
        return self


class SessionBlueprintSegmentGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionBlueprintSegmentGraphQLField":
        self._alias = alias
        return self


class SessionBlueprintSessionCreationFailedContextGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "SessionBlueprintSessionCreationFailedContextGraphQLField":
        self._alias = alias
        return self


class SessionBlueprintSessionCreationSkippedAthletesContextGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "SessionBlueprintSessionCreationSkippedAthletesContextGraphQLField":
        self._alias = alias
        return self


class SessionBlueprintSessionCreationSkippedGatewaysContextGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "SessionBlueprintSessionCreationSkippedGatewaysContextGraphQLField":
        self._alias = alias
        return self


class SessionLoadHistoryGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionLoadHistoryGraphQLField":
        self._alias = alias
        return self


class SessionLoadHistoryEntryGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionLoadHistoryEntryGraphQLField":
        self._alias = alias
        return self


class SessionMetricsUpdatedSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "SessionMetricsUpdatedSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class SessionParticipationGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionParticipationGraphQLField":
        self._alias = alias
        return self


class SessionPlanGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionPlanGraphQLField":
        self._alias = alias
        return self


class SessionQuickActionsSubscriptionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionQuickActionsSubscriptionPayloadGraphQLField":
        self._alias = alias
        return self


class SessionSummaryGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionSummaryGraphQLField":
        self._alias = alias
        return self


class SessionTagDefinitionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionTagDefinitionGraphQLField":
        self._alias = alias
        return self


class SessionVideoGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionVideoGraphQLField":
        self._alias = alias
        return self


class SessionWarningsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SessionWarningsGraphQLField":
        self._alias = alias
        return self


class SetBenchedPlayersPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SetBenchedPlayersPayloadGraphQLField":
        self._alias = alias
        return self


class SetCustomMaxMetricPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SetCustomMaxMetricPayloadGraphQLField":
        self._alias = alias
        return self


class SettingsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SettingsGraphQLField":
        self._alias = alias
        return self


class SpeedzoneLowerBoundsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SpeedzoneLowerBoundsGraphQLField":
        self._alias = alias
        return self


class SpeedzonesPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SpeedzonesPayloadGraphQLField":
        self._alias = alias
        return self


class SportDefinitionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SportDefinitionGraphQLField":
        self._alias = alias
        return self


class StaffGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "StaffGraphQLField":
        self._alias = alias
        return self


class StripeSubscriptionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "StripeSubscriptionGraphQLField":
        self._alias = alias
        return self


class SurveyGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SurveyGraphQLField":
        self._alias = alias
        return self


class SurveyAggregateUnion(GraphQLField):
    def on(self, type_name: str, *subfields: GraphQLField) -> "SurveyAggregateUnion":
        self._inline_fragments[type_name] = subfields
        return self

    def alias(self, alias: str) -> "SurveyAggregateUnion":
        self._alias = alias
        return self


class SurveyAnswerGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SurveyAnswerGraphQLField":
        self._alias = alias
        return self


class SurveyAssignmentGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SurveyAssignmentGraphQLField":
        self._alias = alias
        return self


class SurveyCompletedContextGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SurveyCompletedContextGraphQLField":
        self._alias = alias
        return self


class SurveyDistributionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SurveyDistributionGraphQLField":
        self._alias = alias
        return self


class SurveyQuestionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SurveyQuestionGraphQLField":
        self._alias = alias
        return self


class SurveyReminderContextGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SurveyReminderContextGraphQLField":
        self._alias = alias
        return self


class SurveyTimerTriggerGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SurveyTimerTriggerGraphQLField":
        self._alias = alias
        return self


class SyncableUnionUnion(GraphQLField):
    def on(self, type_name: str, *subfields: GraphQLField) -> "SyncableUnionUnion":
        self._inline_fragments[type_name] = subfields
        return self

    def alias(self, alias: str) -> "SyncableUnionUnion":
        self._alias = alias
        return self


class TagDefinitionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TagDefinitionGraphQLField":
        self._alias = alias
        return self


class TimeRangeDataGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TimeRangeDataGraphQLField":
        self._alias = alias
        return self


class TimeSeriesDataGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TimeSeriesDataGraphQLField":
        self._alias = alias
        return self


class TimelineDayGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TimelineDayGraphQLField":
        self._alias = alias
        return self


class TimelineItemGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TimelineItemGraphQLField":
        self._alias = alias
        return self


class TopPerformersGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TopPerformersGraphQLField":
        self._alias = alias
        return self


class TrainingSessionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TrainingSessionGraphQLField":
        self._alias = alias
        return self


class TrainingSessionAthleteMetricSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TrainingSessionAthleteMetricSetGraphQLField":
        self._alias = alias
        return self


class TrainingSessionLinkGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TrainingSessionLinkGraphQLField":
        self._alias = alias
        return self


class TrainingSessionMetricSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TrainingSessionMetricSetGraphQLField":
        self._alias = alias
        return self


class TrainingSessionParticipationGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TrainingSessionParticipationGraphQLField":
        self._alias = alias
        return self


class TrainingSessionSegmentAthleteMetricSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TrainingSessionSegmentAthleteMetricSetGraphQLField":
        self._alias = alias
        return self


class TrainingSessionSegmentMetricSetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TrainingSessionSegmentMetricSetGraphQLField":
        self._alias = alias
        return self


class TriggerSessionDetectionV2PayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TriggerSessionDetectionV2PayloadGraphQLField":
        self._alias = alias
        return self


class UnarchiveClubMemberPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UnarchiveClubMemberPayloadGraphQLField":
        self._alias = alias
        return self


class UnitOptionsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UnitOptionsGraphQLField":
        self._alias = alias
        return self


class UpdateAthleteGroupPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateAthleteGroupPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateAthletePayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateAthletePayloadGraphQLField":
        self._alias = alias
        return self


class UpdateClubMemberPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateClubMemberPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateClubSettingsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateClubSettingsPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateCustomQuestionDefinitionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateCustomQuestionDefinitionPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateDatasetPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateDatasetPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateDevicePayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateDevicePayloadGraphQLField":
        self._alias = alias
        return self


class UpdateFlexibleReportChartPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateFlexibleReportChartPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateFlexibleReportChartPositionPayloadGraphQLField(GraphQLField):
    def alias(
        self, alias: str
    ) -> "UpdateFlexibleReportChartPositionPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateFlexibleReportPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateFlexibleReportPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateGatewayOwnershipPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateGatewayOwnershipPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateMatchEventPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateMatchEventPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateMatchEventsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateMatchEventsPayloadGraphQLField":
        self._alias = alias
        return self


class UpdatePersonDetailsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdatePersonDetailsPayloadGraphQLField":
        self._alias = alias
        return self


class UpdatePitchPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdatePitchPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateSegmentPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateSegmentPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateSegmentsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateSegmentsPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateSessionBlueprintPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateSessionBlueprintPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateSessionParticipationsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateSessionParticipationsPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateSessionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateSessionPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateSessionPositionsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateSessionPositionsPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateSessionTagDefinitionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateSessionTagDefinitionPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateStaffBillingPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateStaffBillingPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateSurveyPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateSurveyPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateSurveyTimerTriggerPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateSurveyTimerTriggerPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateTagDefinitionPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateTagDefinitionPayloadGraphQLField":
        self._alias = alias
        return self


class UpdateUserPreferencesPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpdateUserPreferencesPayloadGraphQLField":
        self._alias = alias
        return self


class UpsertChatClubContextPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpsertChatClubContextPayloadGraphQLField":
        self._alias = alias
        return self


class UpsertChatCoachContextPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpsertChatCoachContextPayloadGraphQLField":
        self._alias = alias
        return self


class UpsertDataRecordingsPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpsertDataRecordingsPayloadGraphQLField":
        self._alias = alias
        return self


class UpsertSessionPlanPayloadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UpsertSessionPlanPayloadGraphQLField":
        self._alias = alias
        return self


class UserPreferenceGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "UserPreferenceGraphQLField":
        self._alias = alias
        return self


class ValidationErrorGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ValidationErrorGraphQLField":
        self._alias = alias
        return self


class VideoFragmentGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "VideoFragmentGraphQLField":
        self._alias = alias
        return self


class VideoRecordingGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "VideoRecordingGraphQLField":
        self._alias = alias
        return self


class VideoSourceInterfaceGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "VideoSourceInterfaceGraphQLField":
        self._alias = alias
        return self


class VideoVariantGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "VideoVariantGraphQLField":
        self._alias = alias
        return self


class WeeklyLoadGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "WeeklyLoadGraphQLField":
        self._alias = alias
        return self


class WeeklyLoadAthleteGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "WeeklyLoadAthleteGraphQLField":
        self._alias = alias
        return self
