# Generated by ariadne-codegen

from typing import Any, Optional

from .enums import (
    CustomMaxMetricEnum,
    DeviceOwnerType,
    DeviceTypeEnum,
    EdgeOwnerType,
    OwnerEnum,
    Platform,
    RatingEnum,
)
from .custom_fields import (
    AccelzonesPayloadFields,
    AcceptPrivacyPolicyPayloadFields,
    AddAthleteGroupPayloadFields,
    AddExistingPersonToClubPayloadFields,
    AddNewPersonToClubPayloadFields,
    AddSurveyAnswerPayloadFields,
    ArchiveClubMemberPayloadFields,
    ArchivePitchPayloadFields,
    ArchiveSurveyPayloadFields,
    AssignDevicePayloadFields,
    AssignEdgePayloadFields,
    BulkApprovePayloadFields,
    ClaimPersonPayloadFields,
    ClubMutationFields,
    CreateCustomQuestionDefinitionPayloadFields,
    CreateDatasetPayloadFields,
    CreateDeviceSyncPayloadFields,
    CreateEdgeNamePayloadFields,
    CreateFlexibleReportChartPayloadFields,
    CreateFlexibleReportPayloadFields,
    CreateMatchEventPayloadFields,
    CreateMatchEventsPayloadFields,
    CreatePitchPayloadFields,
    CreateQuestionPayloadFields,
    CreateReportPayloadFields,
    CreateResponsePayloadFields,
    CreateSegmentPayloadFields,
    CreateSessionPayloadFields,
    CreateSessionTagDefinitionPayloadFields,
    CreateSurveyPayloadFields,
    CreateSurveyTimerTriggerPayloadFields,
    CreateTagDefinitionPayloadFields,
    CreateVideoRecordingPayloadFields,
    DecelzonesPayloadFields,
    DeleteAccelzonesPayloadFields,
    DeleteDecelzonesPayloadFields,
    DeleteHeartRateBoundsPayloadFields,
    DeleteSpeedzonesPayloadFields,
    DestroyAppMessagePayloadFields,
    DestroyAthleteGroupPayloadFields,
    DestroyCustomQuestionDefinitionPayloadFields,
    DestroyDatasetPayloadFields,
    DestroyFlexibleReportChartsPayloadFields,
    DestroyFlexibleReportsPayloadFields,
    DestroyMatchEventPayloadFields,
    DestroyMatchEventsPayloadFields,
    DestroySegmentPayloadFields,
    DestroySessionBlueprintPayloadFields,
    DestroySessionPayloadFields,
    DestroySessionTagDefinitionPayloadFields,
    DestroyTagDefinitionPayloadFields,
    DuplicateFlexibleReportPayloadFields,
    DuplicateSegmentPayloadFields,
    DuplicateSessionPayloadFields,
    DuplicateSurveyPayloadFields,
    EndEdgeOwnershipPayloadFields,
    HeartRateBoundsPayloadFields,
    MarkAppMessageReadPayloadFields,
    MarkMultipleAppMessagesReadPayloadFields,
    ProvisionGatewayPayloadFields,
    RateResponsePayloadFields,
    RecreateGatewaySessionsPayloadFields,
    RegisterDevicePayloadFields,
    RelativeAccelzonesPayloadFields,
    RelativeDecelzonesPayloadFields,
    RelativeSpeedzonesPayloadFields,
    RemoveSurveyTimerTriggerPayloadFields,
    ResendConfirmationEmailPayloadFields,
    ResendReportPayloadFields,
    RespondToDetectedMatchEventPayloadFields,
    RespondToDetectedMatchEventsPayloadFields,
    ReviewPendingMemberPayloadFields,
    RotateLiveDataKeysPayloadFields,
    SetBenchedPlayersPayloadFields,
    SetCustomMaxMetricPayloadFields,
    SpeedzonesPayloadFields,
    TriggerSessionDetectionV2PayloadFields,
    UnarchiveClubMemberPayloadFields,
    UpdateAthleteGroupPayloadFields,
    UpdateAthletePayloadFields,
    UpdateClubMemberPayloadFields,
    UpdateClubSettingsPayloadFields,
    UpdateCustomQuestionDefinitionPayloadFields,
    UpdateDatasetPayloadFields,
    UpdateDevicePayloadFields,
    UpdateFlexibleReportChartPayloadFields,
    UpdateFlexibleReportChartPositionPayloadFields,
    UpdateFlexibleReportPayloadFields,
    UpdateGatewayOwnershipPayloadFields,
    UpdateMatchEventPayloadFields,
    UpdateMatchEventsPayloadFields,
    UpdatePersonDetailsPayloadFields,
    UpdatePitchPayloadFields,
    UpdateSegmentPayloadFields,
    UpdateSegmentsPayloadFields,
    UpdateSessionBlueprintPayloadFields,
    UpdateSessionParticipationsPayloadFields,
    UpdateSessionPayloadFields,
    UpdateSessionPositionsPayloadFields,
    UpdateSessionTagDefinitionPayloadFields,
    UpdateStaffBillingPayloadFields,
    UpdateSurveyPayloadFields,
    UpdateSurveyTimerTriggerPayloadFields,
    UpdateTagDefinitionPayloadFields,
    UpdateUserPreferencesPayloadFields,
    UpsertChatClubContextPayloadFields,
    UpsertChatCoachContextPayloadFields,
    UpsertDataRecordingsPayloadFields,
    UpsertSessionPlanPayloadFields,
)
from .input_types import (
    AthleteAccelzoneAttributes,
    AthleteDecelzoneAttributes,
    AthleteGroupAttributes,
    AthleteHeartRateBoundsAttributes,
    AthleteRelativeAccelzoneAttributes,
    AthleteRelativeDecelzoneAttributes,
    AthleteSpeedzoneAttributes,
    BulkUpdateMatchEventAttributes,
    ClaimPersonAttributes,
    ClubContextAttributes,
    CoachContextAttributesInput,
    CreateDeviceSyncInput,
    CreateFlexibleReportChartAttributes,
    CustomQuestionDefinitionAttributes,
    DatasetAttributes,
    DeviceAttributes,
    DuplicateSessionAttributes,
    FlexibleReportAttributes,
    GatewaySessionAttributes,
    MatchEventAttributes,
    MutateSessionAttributes,
    MutateSessionBlueprintAttributes,
    NewPersonAttributes,
    PitchAttributes,
    RelativeSpeedzoneAttributes,
    ReportAttributes,
    SegmentAttributes,
    SegmentPatch,
    SessionParticipationAttributes,
    SessionPlanAttributesInput,
    SessionPositionsAttributes,
    SessionTagDefinitionAttributes,
    SurveyAnswerAttributes,
    SurveyAttributes,
    SurveyTimerTriggerAttributes,
    TagDefinitionAttributes,
    TaggerAttributes,
    UpdateAthleteAttributes,
    UpdateClubMemberAttributes,
    UpdateClubSettingsAttributes,
    UpdateDatasetAttributes,
    UpdateFlexibleReportAttributes,
    UpdateFlexibleReportChartAttributes,
    UpdateGatewayOwnershipAttributes,
    UpdatePersonAttributes,
    UpdateStaffBillingAttributes,
    UpdateUserPreferencesAttributes,
    UpsertDataRecordingsAttributes,
    VideoRecordingAttributes,
)


class Mutation:
    @classmethod
    def accept_privacy_policy(cls, policy_id: str) -> AcceptPrivacyPolicyPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "policyId": {"type": "ID!", "value": policy_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return AcceptPrivacyPolicyPayloadFields(
            field_name="acceptPrivacyPolicy", arguments=cleared_arguments
        )

    @classmethod
    def add_athlete_group(
        cls, attributes: AthleteGroupAttributes
    ) -> AddAthleteGroupPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "AthleteGroupAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return AddAthleteGroupPayloadFields(
            field_name="addAthleteGroup", arguments=cleared_arguments
        )

    @classmethod
    def add_existing_person_to_club(
        cls,
        signup_token: str,
        *,
        person_attributes: Optional[UpdatePersonAttributes] = None,
    ) -> AddExistingPersonToClubPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "personAttributes": {
                "type": "UpdatePersonAttributes",
                "value": person_attributes,
            },
            "signupToken": {"type": "String!", "value": signup_token},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return AddExistingPersonToClubPayloadFields(
            field_name="addExistingPersonToClub", arguments=cleared_arguments
        )

    @classmethod
    def add_new_person_to_club(
        cls, attributes: NewPersonAttributes
    ) -> AddNewPersonToClubPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "NewPersonAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return AddNewPersonToClubPayloadFields(
            field_name="addNewPersonToClub", arguments=cleared_arguments
        )

    @classmethod
    def add_survey_answer(
        cls, attributes: SurveyAnswerAttributes
    ) -> AddSurveyAnswerPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "SurveyAnswerAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return AddSurveyAnswerPayloadFields(
            field_name="addSurveyAnswer", arguments=cleared_arguments
        )

    @classmethod
    def approve_all_pending_members(cls, ids: list[str]) -> BulkApprovePayloadFields:
        arguments: dict[str, dict[str, Any]] = {"ids": {"type": "[ID!]!", "value": ids}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return BulkApprovePayloadFields(
            field_name="approveAllPendingMembers", arguments=cleared_arguments
        )

    @classmethod
    def archive_club_member(
        cls, club_id: str, id: str
    ) -> ArchiveClubMemberPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "clubId": {"type": "ID!", "value": club_id},
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ArchiveClubMemberPayloadFields(
            field_name="archiveClubMember", arguments=cleared_arguments
        )

    @classmethod
    def archive_pitch(cls, id: str) -> ArchivePitchPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ArchivePitchPayloadFields(
            field_name="archivePitch", arguments=cleared_arguments
        )

    @classmethod
    def archive_survey(cls, id: str) -> ArchiveSurveyPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ArchiveSurveyPayloadFields(
            field_name="archiveSurvey", arguments=cleared_arguments
        )

    @classmethod
    def assign_device(
        cls,
        owner_id: str,
        owner_type: DeviceOwnerType,
        serial_number: Any,
        type: DeviceTypeEnum,
    ) -> AssignDevicePayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "ownerId": {"type": "ID!", "value": owner_id},
            "ownerType": {"type": "DeviceOwnerType!", "value": owner_type},
            "serialNumber": {"type": "BigInt!", "value": serial_number},
            "type": {"type": "DeviceTypeEnum!", "value": type},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return AssignDevicePayloadFields(
            field_name="assignDevice", arguments=cleared_arguments
        )

    @classmethod
    def assign_edge(
        cls, edge_id: str, owner_id: str, owner_type: EdgeOwnerType
    ) -> AssignEdgePayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "edgeId": {"type": "ID!", "value": edge_id},
            "ownerId": {"type": "ID!", "value": owner_id},
            "ownerType": {"type": "EdgeOwnerType!", "value": owner_type},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return AssignEdgePayloadFields(
            field_name="assignEdge", arguments=cleared_arguments
        )

    @classmethod
    def athletes_accelzones(
        cls, attributes: AthleteAccelzoneAttributes
    ) -> AccelzonesPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "AthleteAccelzoneAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return AccelzonesPayloadFields(
            field_name="athletesAccelzones", arguments=cleared_arguments
        )

    @classmethod
    def athletes_decelzones(
        cls, attributes: AthleteDecelzoneAttributes
    ) -> DecelzonesPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "AthleteDecelzoneAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DecelzonesPayloadFields(
            field_name="athletesDecelzones", arguments=cleared_arguments
        )

    @classmethod
    def athletes_delete_accelzones(
        cls, athlete_ids: list[str], *, reprocess: Optional[bool] = None
    ) -> DeleteAccelzonesPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reprocess": {"type": "Boolean", "value": reprocess},
            "athleteIds": {"type": "[ID!]!", "value": athlete_ids},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DeleteAccelzonesPayloadFields(
            field_name="athletesDeleteAccelzones", arguments=cleared_arguments
        )

    @classmethod
    def athletes_delete_decelzones(
        cls, athlete_ids: list[str], *, reprocess: Optional[bool] = None
    ) -> DeleteDecelzonesPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reprocess": {"type": "Boolean", "value": reprocess},
            "athleteIds": {"type": "[ID!]!", "value": athlete_ids},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DeleteDecelzonesPayloadFields(
            field_name="athletesDeleteDecelzones", arguments=cleared_arguments
        )

    @classmethod
    def athletes_delete_heart_rate_bounds(
        cls, athlete_ids: list[str], *, reprocess: Optional[bool] = None
    ) -> DeleteHeartRateBoundsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reprocess": {"type": "Boolean", "value": reprocess},
            "athleteIds": {"type": "[ID!]!", "value": athlete_ids},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DeleteHeartRateBoundsPayloadFields(
            field_name="athletesDeleteHeartRateBounds", arguments=cleared_arguments
        )

    @classmethod
    def athletes_delete_speedzones(
        cls, athlete_ids: list[str], *, reprocess: Optional[bool] = None
    ) -> DeleteSpeedzonesPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reprocess": {"type": "Boolean", "value": reprocess},
            "athleteIds": {"type": "[ID!]!", "value": athlete_ids},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DeleteSpeedzonesPayloadFields(
            field_name="athletesDeleteSpeedzones", arguments=cleared_arguments
        )

    @classmethod
    def athletes_heart_rate_bounds(
        cls,
        attributes: AthleteHeartRateBoundsAttributes,
        *,
        reprocess: Optional[bool] = None,
    ) -> HeartRateBoundsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reprocess": {"type": "Boolean", "value": reprocess},
            "attributes": {
                "type": "AthleteHeartRateBoundsAttributes!",
                "value": attributes,
            },
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return HeartRateBoundsPayloadFields(
            field_name="athletesHeartRateBounds", arguments=cleared_arguments
        )

    @classmethod
    def athletes_relative_accelzones(
        cls,
        attributes: AthleteRelativeAccelzoneAttributes,
        *,
        reprocess: Optional[bool] = None,
    ) -> RelativeAccelzonesPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reprocess": {"type": "Boolean", "value": reprocess},
            "attributes": {
                "type": "AthleteRelativeAccelzoneAttributes!",
                "value": attributes,
            },
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return RelativeAccelzonesPayloadFields(
            field_name="athletesRelativeAccelzones", arguments=cleared_arguments
        )

    @classmethod
    def athletes_relative_decelzones(
        cls,
        attributes: AthleteRelativeDecelzoneAttributes,
        *,
        reprocess: Optional[bool] = None,
    ) -> RelativeDecelzonesPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reprocess": {"type": "Boolean", "value": reprocess},
            "attributes": {
                "type": "AthleteRelativeDecelzoneAttributes!",
                "value": attributes,
            },
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return RelativeDecelzonesPayloadFields(
            field_name="athletesRelativeDecelzones", arguments=cleared_arguments
        )

    @classmethod
    def athletes_relative_speedzones(
        cls,
        attributes: RelativeSpeedzoneAttributes,
        *,
        reprocess: Optional[bool] = None,
    ) -> RelativeSpeedzonesPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reprocess": {"type": "Boolean", "value": reprocess},
            "attributes": {"type": "RelativeSpeedzoneAttributes!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return RelativeSpeedzonesPayloadFields(
            field_name="athletesRelativeSpeedzones", arguments=cleared_arguments
        )

    @classmethod
    def athletes_speedzones(
        cls, attributes: AthleteSpeedzoneAttributes, *, reprocess: Optional[bool] = None
    ) -> SpeedzonesPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "AthleteSpeedzoneAttributes!", "value": attributes},
            "reprocess": {"type": "Boolean", "value": reprocess},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return SpeedzonesPayloadFields(
            field_name="athletesSpeedzones", arguments=cleared_arguments
        )

    @classmethod
    def claim_person(
        cls, attributes: ClaimPersonAttributes
    ) -> ClaimPersonPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "ClaimPersonAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ClaimPersonPayloadFields(
            field_name="claimPerson", arguments=cleared_arguments
        )

    @classmethod
    def club(cls, id: str) -> ClubMutationFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ClubMutationFields(field_name="club", arguments=cleared_arguments)

    @classmethod
    def create_chat_response(
        cls, question_id: str, response: str
    ) -> CreateResponsePayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "questionId": {"type": "ID!", "value": question_id},
            "response": {"type": "String!", "value": response},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateResponsePayloadFields(
            field_name="createChatResponse", arguments=cleared_arguments
        )

    @classmethod
    def create_custom_question_definition(
        cls, attributes: CustomQuestionDefinitionAttributes, club_id: str
    ) -> CreateCustomQuestionDefinitionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "CustomQuestionDefinitionAttributes!",
                "value": attributes,
            },
            "clubId": {"type": "ID!", "value": club_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateCustomQuestionDefinitionPayloadFields(
            field_name="createCustomQuestionDefinition", arguments=cleared_arguments
        )

    @classmethod
    def create_dataset(
        cls, attributes: DatasetAttributes
    ) -> CreateDatasetPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "DatasetAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateDatasetPayloadFields(
            field_name="createDataset", arguments=cleared_arguments
        )

    @classmethod
    def create_device_sync(
        cls, input: CreateDeviceSyncInput
    ) -> CreateDeviceSyncPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "input": {"type": "CreateDeviceSyncInput!", "value": input}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateDeviceSyncPayloadFields(
            field_name="createDeviceSync", arguments=cleared_arguments
        )

    @classmethod
    def create_edge_name(cls, edge_id: str, name: str) -> CreateEdgeNamePayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "edgeId": {"type": "ID!", "value": edge_id},
            "name": {"type": "String!", "value": name},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateEdgeNamePayloadFields(
            field_name="createEdgeName", arguments=cleared_arguments
        )

    @classmethod
    def create_flexible_report(
        cls, attributes: FlexibleReportAttributes
    ) -> CreateFlexibleReportPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "FlexibleReportAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateFlexibleReportPayloadFields(
            field_name="createFlexibleReport", arguments=cleared_arguments
        )

    @classmethod
    def create_flexible_report_chart(
        cls, attributes: CreateFlexibleReportChartAttributes
    ) -> CreateFlexibleReportChartPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "CreateFlexibleReportChartAttributes!",
                "value": attributes,
            }
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateFlexibleReportChartPayloadFields(
            field_name="createFlexibleReportChart", arguments=cleared_arguments
        )

    @classmethod
    def create_match_event(
        cls, session_id: str, attributes: MatchEventAttributes
    ) -> CreateMatchEventPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "sessionId": {"type": "ID!", "value": session_id},
            "attributes": {"type": "MatchEventAttributes!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateMatchEventPayloadFields(
            field_name="createMatchEvent", arguments=cleared_arguments
        )

    @classmethod
    def create_match_events(
        cls, session_id: str, attributes: list[MatchEventAttributes]
    ) -> CreateMatchEventsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "sessionId": {"type": "ID!", "value": session_id},
            "attributes": {"type": "[MatchEventAttributes!]!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateMatchEventsPayloadFields(
            field_name="createMatchEvents", arguments=cleared_arguments
        )

    @classmethod
    def create_pitch(
        cls,
        attributes: PitchAttributes,
        *,
        detected_session_id: Optional[str] = None,
        owner_id: Optional[str] = None,
        owner_type: Optional[OwnerEnum] = None,
    ) -> CreatePitchPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "detectedSessionId": {"type": "ID", "value": detected_session_id},
            "ownerId": {"type": "ID", "value": owner_id},
            "ownerType": {"type": "OwnerEnum", "value": owner_type},
            "attributes": {"type": "PitchAttributes!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreatePitchPayloadFields(
            field_name="createPitch", arguments=cleared_arguments
        )

    @classmethod
    def create_question(
        cls, question: str, staff_id: str
    ) -> CreateQuestionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "question": {"type": "String!", "value": question},
            "staffId": {"type": "ID!", "value": staff_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateQuestionPayloadFields(
            field_name="createQuestion", arguments=cleared_arguments
        )

    @classmethod
    def create_report(cls, attributes: ReportAttributes) -> CreateReportPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "ReportAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateReportPayloadFields(
            field_name="createReport", arguments=cleared_arguments
        )

    @classmethod
    def create_session(
        cls, attributes: MutateSessionAttributes
    ) -> CreateSessionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "MutateSessionAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateSessionPayloadFields(
            field_name="createSession", arguments=cleared_arguments
        )

    @classmethod
    def create_session_segment(
        cls, attributes: SegmentAttributes, *, id: Optional[str] = None
    ) -> CreateSegmentPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID", "value": id},
            "attributes": {"type": "SegmentAttributes!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateSegmentPayloadFields(
            field_name="createSessionSegment", arguments=cleared_arguments
        )

    @classmethod
    def create_session_tag_definition(
        cls, club_id: str, attributes: SessionTagDefinitionAttributes
    ) -> CreateSessionTagDefinitionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "clubId": {"type": "ID!", "value": club_id},
            "attributes": {
                "type": "SessionTagDefinitionAttributes!",
                "value": attributes,
            },
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateSessionTagDefinitionPayloadFields(
            field_name="createSessionTagDefinition", arguments=cleared_arguments
        )

    @classmethod
    def create_survey(
        cls, attributes: SurveyAttributes, club_id: str
    ) -> CreateSurveyPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "SurveyAttributes!", "value": attributes},
            "clubId": {"type": "ID!", "value": club_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateSurveyPayloadFields(
            field_name="createSurvey", arguments=cleared_arguments
        )

    @classmethod
    def create_survey_timer_trigger(
        cls, attributes: SurveyTimerTriggerAttributes
    ) -> CreateSurveyTimerTriggerPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "SurveyTimerTriggerAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateSurveyTimerTriggerPayloadFields(
            field_name="createSurveyTimerTrigger", arguments=cleared_arguments
        )

    @classmethod
    def create_tag_definition(
        cls, attributes: TagDefinitionAttributes, tagger: TaggerAttributes
    ) -> CreateTagDefinitionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "TagDefinitionAttributes!", "value": attributes},
            "tagger": {"type": "TaggerAttributes!", "value": tagger},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateTagDefinitionPayloadFields(
            field_name="createTagDefinition", arguments=cleared_arguments
        )

    @classmethod
    def create_video_recording(
        cls, attributes: VideoRecordingAttributes
    ) -> CreateVideoRecordingPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "VideoRecordingAttributes!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CreateVideoRecordingPayloadFields(
            field_name="createVideoRecording", arguments=cleared_arguments
        )

    @classmethod
    def destroy_athlete_group(cls, group_id: str) -> DestroyAthleteGroupPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "groupId": {"type": "ID!", "value": group_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroyAthleteGroupPayloadFields(
            field_name="destroyAthleteGroup", arguments=cleared_arguments
        )

    @classmethod
    def destroy_custom_question_definition(
        cls, id: str, club_id: str
    ) -> DestroyCustomQuestionDefinitionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "clubId": {"type": "ID!", "value": club_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroyCustomQuestionDefinitionPayloadFields(
            field_name="destroyCustomQuestionDefinition", arguments=cleared_arguments
        )

    @classmethod
    def destroy_dataset(cls, id: str) -> DestroyDatasetPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroyDatasetPayloadFields(
            field_name="destroyDataset", arguments=cleared_arguments
        )

    @classmethod
    def destroy_flexible_report_charts(
        cls, chart_ids: list[str]
    ) -> DestroyFlexibleReportChartsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "chartIds": {"type": "[ID!]!", "value": chart_ids}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroyFlexibleReportChartsPayloadFields(
            field_name="destroyFlexibleReportCharts", arguments=cleared_arguments
        )

    @classmethod
    def destroy_flexible_reports(
        cls, report_ids: list[str]
    ) -> DestroyFlexibleReportsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reportIds": {"type": "[ID!]!", "value": report_ids}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroyFlexibleReportsPayloadFields(
            field_name="destroyFlexibleReports", arguments=cleared_arguments
        )

    @classmethod
    def destroy_match_event(cls, id: str) -> DestroyMatchEventPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroyMatchEventPayloadFields(
            field_name="destroyMatchEvent", arguments=cleared_arguments
        )

    @classmethod
    def destroy_match_events(cls, ids: list[str]) -> DestroyMatchEventsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"ids": {"type": "[ID!]!", "value": ids}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroyMatchEventsPayloadFields(
            field_name="destroyMatchEvents", arguments=cleared_arguments
        )

    @classmethod
    def destroy_session(cls, id: str) -> DestroySessionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroySessionPayloadFields(
            field_name="destroySession", arguments=cleared_arguments
        )

    @classmethod
    def destroy_session_blueprint(cls, id: str) -> DestroySessionBlueprintPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroySessionBlueprintPayloadFields(
            field_name="destroySessionBlueprint", arguments=cleared_arguments
        )

    @classmethod
    def destroy_session_segment(cls, id: str) -> DestroySegmentPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroySegmentPayloadFields(
            field_name="destroySessionSegment", arguments=cleared_arguments
        )

    @classmethod
    def destroy_session_tag_definition(
        cls, id: str
    ) -> DestroySessionTagDefinitionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroySessionTagDefinitionPayloadFields(
            field_name="destroySessionTagDefinition", arguments=cleared_arguments
        )

    @classmethod
    def destroy_tag_definition(cls, id: str) -> DestroyTagDefinitionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroyTagDefinitionPayloadFields(
            field_name="destroyTagDefinition", arguments=cleared_arguments
        )

    @classmethod
    def dismiss_app_message(cls, id: str) -> DestroyAppMessagePayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DestroyAppMessagePayloadFields(
            field_name="dismissAppMessage", arguments=cleared_arguments
        )

    @classmethod
    def duplicate_flexible_report(
        cls, club_id: str, id: str
    ) -> DuplicateFlexibleReportPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "clubId": {"type": "ID!", "value": club_id},
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DuplicateFlexibleReportPayloadFields(
            field_name="duplicateFlexibleReport", arguments=cleared_arguments
        )

    @classmethod
    def duplicate_session(
        cls, attributes: DuplicateSessionAttributes, id: str
    ) -> DuplicateSessionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "DuplicateSessionAttributes!", "value": attributes},
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DuplicateSessionPayloadFields(
            field_name="duplicateSession", arguments=cleared_arguments
        )

    @classmethod
    def duplicate_session_segment(cls, id: str) -> DuplicateSegmentPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DuplicateSegmentPayloadFields(
            field_name="duplicateSessionSegment", arguments=cleared_arguments
        )

    @classmethod
    def duplicate_survey(
        cls, attributes: SurveyAttributes, id: str, club_id: str
    ) -> DuplicateSurveyPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "SurveyAttributes!", "value": attributes},
            "id": {"type": "ID!", "value": id},
            "clubId": {"type": "ID!", "value": club_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DuplicateSurveyPayloadFields(
            field_name="duplicateSurvey", arguments=cleared_arguments
        )

    @classmethod
    def end_edge_ownership(cls, edge_id: str) -> EndEdgeOwnershipPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "edgeId": {"type": "ID!", "value": edge_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return EndEdgeOwnershipPayloadFields(
            field_name="endEdgeOwnership", arguments=cleared_arguments
        )

    @classmethod
    def mark_app_message_read(cls, id: str) -> MarkAppMessageReadPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return MarkAppMessageReadPayloadFields(
            field_name="markAppMessageRead", arguments=cleared_arguments
        )

    @classmethod
    def mark_multiple_app_messages_read(
        cls, ids: list[str]
    ) -> MarkMultipleAppMessagesReadPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"ids": {"type": "[ID!]!", "value": ids}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return MarkMultipleAppMessagesReadPayloadFields(
            field_name="markMultipleAppMessagesRead", arguments=cleared_arguments
        )

    @classmethod
    def provision_gateway(
        cls, serial_number: str, csr: str, firmware_version: str, organisation_id: str
    ) -> ProvisionGatewayPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "serialNumber": {"type": "String!", "value": serial_number},
            "csr": {"type": "String!", "value": csr},
            "firmwareVersion": {"type": "String!", "value": firmware_version},
            "organisationId": {"type": "ID!", "value": organisation_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ProvisionGatewayPayloadFields(
            field_name="provisionGateway", arguments=cleared_arguments
        )

    @classmethod
    def rate_chat_response(
        cls,
        response_id: str,
        *,
        rating: Optional[RatingEnum] = None,
        rating_explanation: Optional[str] = None,
    ) -> RateResponsePayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "rating": {"type": "RatingEnum", "value": rating},
            "ratingExplanation": {"type": "String", "value": rating_explanation},
            "responseId": {"type": "ID!", "value": response_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return RateResponsePayloadFields(
            field_name="rateChatResponse", arguments=cleared_arguments
        )

    @classmethod
    def recreate_gateway_sessions(
        cls,
        attributes: list[GatewaySessionAttributes],
        *,
        session_id: Optional[str] = None,
    ) -> RecreateGatewaySessionsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "[GatewaySessionAttributes!]!", "value": attributes},
            "sessionId": {"type": "ID", "value": session_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return RecreateGatewaySessionsPayloadFields(
            field_name="recreateGatewaySessions", arguments=cleared_arguments
        )

    @classmethod
    def register_device(
        cls, firebase_token: str, *, platform: Optional[Platform] = None
    ) -> RegisterDevicePayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "firebaseToken": {"type": "String!", "value": firebase_token},
            "platform": {"type": "Platform", "value": platform},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return RegisterDevicePayloadFields(
            field_name="registerDevice", arguments=cleared_arguments
        )

    @classmethod
    def remove_survey_timer_trigger(
        cls, survey_timer_trigger_id: str
    ) -> RemoveSurveyTimerTriggerPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "surveyTimerTriggerId": {"type": "ID!", "value": survey_timer_trigger_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return RemoveSurveyTimerTriggerPayloadFields(
            field_name="removeSurveyTimerTrigger", arguments=cleared_arguments
        )

    @classmethod
    def resend_pending_member_confirmation_email(
        cls, id: str
    ) -> ResendConfirmationEmailPayloadFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ResendConfirmationEmailPayloadFields(
            field_name="resendPendingMemberConfirmationEmail",
            arguments=cleared_arguments,
        )

    @classmethod
    def resend_report(
        cls, report_id: str, *, regenerate: Optional[bool] = None
    ) -> ResendReportPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reportId": {"type": "ID!", "value": report_id},
            "regenerate": {"type": "Boolean", "value": regenerate},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ResendReportPayloadFields(
            field_name="resendReport", arguments=cleared_arguments
        )

    @classmethod
    def respond_to_detected_match_event(
        cls, id: str, accept_event: bool
    ) -> RespondToDetectedMatchEventPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "acceptEvent": {"type": "Boolean!", "value": accept_event},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return RespondToDetectedMatchEventPayloadFields(
            field_name="respondToDetectedMatchEvent", arguments=cleared_arguments
        )

    @classmethod
    def respond_to_detected_match_events(
        cls, ids: list[str], accept_event: bool
    ) -> RespondToDetectedMatchEventsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "ids": {"type": "[ID!]!", "value": ids},
            "acceptEvent": {"type": "Boolean!", "value": accept_event},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return RespondToDetectedMatchEventsPayloadFields(
            field_name="respondToDetectedMatchEvents", arguments=cleared_arguments
        )

    @classmethod
    def review_pending_member(
        cls, approved: bool, id: str
    ) -> ReviewPendingMemberPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "approved": {"type": "Boolean!", "value": approved},
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ReviewPendingMemberPayloadFields(
            field_name="reviewPendingMember", arguments=cleared_arguments
        )

    @classmethod
    def rotate_live_data_keys(cls, club_id: str) -> RotateLiveDataKeysPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "clubId": {"type": "ID!", "value": club_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return RotateLiveDataKeysPayloadFields(
            field_name="rotateLiveDataKeys", arguments=cleared_arguments
        )

    @classmethod
    def set_benched_players(
        cls, session_id: str, match_session_participations: list[str]
    ) -> SetBenchedPlayersPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "sessionId": {"type": "ID!", "value": session_id},
            "matchSessionParticipations": {
                "type": "[ID!]!",
                "value": match_session_participations,
            },
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return SetBenchedPlayersPayloadFields(
            field_name="setBenchedPlayers", arguments=cleared_arguments
        )

    @classmethod
    def set_custom_max_metric(
        cls,
        athlete_ids: list[str],
        metric: CustomMaxMetricEnum,
        *,
        reprocess: Optional[bool] = None,
        value: Optional[float] = None,
    ) -> SetCustomMaxMetricPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "reprocess": {"type": "Boolean", "value": reprocess},
            "athleteIds": {"type": "[ID!]!", "value": athlete_ids},
            "metric": {"type": "CustomMaxMetricEnum!", "value": metric},
            "value": {"type": "Float", "value": value},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return SetCustomMaxMetricPayloadFields(
            field_name="setCustomMaxMetric", arguments=cleared_arguments
        )

    @classmethod
    def trigger_session_detection_v_2(
        cls, edge_ids: list[str]
    ) -> TriggerSessionDetectionV2PayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "edgeIds": {"type": "[String!]!", "value": edge_ids}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return TriggerSessionDetectionV2PayloadFields(
            field_name="triggerSessionDetectionV2", arguments=cleared_arguments
        )

    @classmethod
    def unarchive_club_member(
        cls, club_id: str, id: str
    ) -> UnarchiveClubMemberPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "clubId": {"type": "ID!", "value": club_id},
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UnarchiveClubMemberPayloadFields(
            field_name="unarchiveClubMember", arguments=cleared_arguments
        )

    @classmethod
    def update_athlete(
        cls, athlete_id: str, attributes: UpdateAthleteAttributes
    ) -> UpdateAthletePayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "athleteId": {"type": "ID!", "value": athlete_id},
            "attributes": {"type": "UpdateAthleteAttributes!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateAthletePayloadFields(
            field_name="updateAthlete", arguments=cleared_arguments
        )

    @classmethod
    def update_athlete_group(
        cls, attributes: AthleteGroupAttributes, group_id: str
    ) -> UpdateAthleteGroupPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "AthleteGroupAttributes!", "value": attributes},
            "groupId": {"type": "ID!", "value": group_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateAthleteGroupPayloadFields(
            field_name="updateAthleteGroup", arguments=cleared_arguments
        )

    @classmethod
    def update_club_member(
        cls, club_id: str, id: str, attributes: UpdateClubMemberAttributes
    ) -> UpdateClubMemberPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "clubId": {"type": "ID!", "value": club_id},
            "id": {"type": "ID!", "value": id},
            "attributes": {"type": "UpdateClubMemberAttributes!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateClubMemberPayloadFields(
            field_name="updateClubMember", arguments=cleared_arguments
        )

    @classmethod
    def update_club_settings(
        cls,
        club_id: str,
        attributes: UpdateClubSettingsAttributes,
        *,
        reprocess: Optional[bool] = None,
    ) -> UpdateClubSettingsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "clubId": {"type": "ID!", "value": club_id},
            "attributes": {
                "type": "UpdateClubSettingsAttributes!",
                "value": attributes,
            },
            "reprocess": {"type": "Boolean", "value": reprocess},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateClubSettingsPayloadFields(
            field_name="updateClubSettings", arguments=cleared_arguments
        )

    @classmethod
    def update_custom_question_definition(
        cls, attributes: CustomQuestionDefinitionAttributes, id: str, club_id: str
    ) -> UpdateCustomQuestionDefinitionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "CustomQuestionDefinitionAttributes!",
                "value": attributes,
            },
            "id": {"type": "ID!", "value": id},
            "clubId": {"type": "ID!", "value": club_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateCustomQuestionDefinitionPayloadFields(
            field_name="updateCustomQuestionDefinition", arguments=cleared_arguments
        )

    @classmethod
    def update_dataset(
        cls, attributes: UpdateDatasetAttributes, id: str
    ) -> UpdateDatasetPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "UpdateDatasetAttributes!", "value": attributes},
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateDatasetPayloadFields(
            field_name="updateDataset", arguments=cleared_arguments
        )

    @classmethod
    def update_device(
        cls, attributes: DeviceAttributes, serial_number: Any, type: DeviceTypeEnum
    ) -> UpdateDevicePayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "DeviceAttributes!", "value": attributes},
            "serialNumber": {"type": "BigInt!", "value": serial_number},
            "type": {"type": "DeviceTypeEnum!", "value": type},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateDevicePayloadFields(
            field_name="updateDevice", arguments=cleared_arguments
        )

    @classmethod
    def update_flexible_report(
        cls, attributes: UpdateFlexibleReportAttributes, id: str
    ) -> UpdateFlexibleReportPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "UpdateFlexibleReportAttributes!",
                "value": attributes,
            },
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateFlexibleReportPayloadFields(
            field_name="updateFlexibleReport", arguments=cleared_arguments
        )

    @classmethod
    def update_flexible_report_chart(
        cls, attributes: UpdateFlexibleReportChartAttributes, id: str
    ) -> UpdateFlexibleReportChartPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "UpdateFlexibleReportChartAttributes!",
                "value": attributes,
            },
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateFlexibleReportChartPayloadFields(
            field_name="updateFlexibleReportChart", arguments=cleared_arguments
        )

    @classmethod
    def update_flexible_report_chart_position(
        cls, id: str, position: int
    ) -> UpdateFlexibleReportChartPositionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "position": {"type": "Int!", "value": position},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateFlexibleReportChartPositionPayloadFields(
            field_name="updateFlexibleReportChartPosition", arguments=cleared_arguments
        )

    @classmethod
    def update_gateway_ownership(
        cls, id: str, attributes: UpdateGatewayOwnershipAttributes
    ) -> UpdateGatewayOwnershipPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "attributes": {
                "type": "UpdateGatewayOwnershipAttributes!",
                "value": attributes,
            },
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateGatewayOwnershipPayloadFields(
            field_name="updateGatewayOwnership", arguments=cleared_arguments
        )

    @classmethod
    def update_match_event(
        cls, id: str, attributes: MatchEventAttributes
    ) -> UpdateMatchEventPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "attributes": {"type": "MatchEventAttributes!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateMatchEventPayloadFields(
            field_name="updateMatchEvent", arguments=cleared_arguments
        )

    @classmethod
    def update_match_events(
        cls, attributes: list[BulkUpdateMatchEventAttributes]
    ) -> UpdateMatchEventsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "[BulkUpdateMatchEventAttributes!]!",
                "value": attributes,
            }
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateMatchEventsPayloadFields(
            field_name="updateMatchEvents", arguments=cleared_arguments
        )

    @classmethod
    def update_person_details(
        cls,
        id: str,
        attributes: UpdatePersonAttributes,
        *,
        reprocess: Optional[bool] = None,
    ) -> UpdatePersonDetailsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "attributes": {"type": "UpdatePersonAttributes!", "value": attributes},
            "reprocess": {"type": "Boolean", "value": reprocess},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdatePersonDetailsPayloadFields(
            field_name="updatePersonDetails", arguments=cleared_arguments
        )

    @classmethod
    def update_pitch(
        cls, pitch_id: str, attributes: PitchAttributes
    ) -> UpdatePitchPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "pitchId": {"type": "ID!", "value": pitch_id},
            "attributes": {"type": "PitchAttributes!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdatePitchPayloadFields(
            field_name="updatePitch", arguments=cleared_arguments
        )

    @classmethod
    def update_session(
        cls, attributes: MutateSessionAttributes, id: str
    ) -> UpdateSessionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "MutateSessionAttributes!", "value": attributes},
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateSessionPayloadFields(
            field_name="updateSession", arguments=cleared_arguments
        )

    @classmethod
    def update_session_blueprint(
        cls, attributes: MutateSessionBlueprintAttributes, id: str
    ) -> UpdateSessionBlueprintPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "MutateSessionBlueprintAttributes!",
                "value": attributes,
            },
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateSessionBlueprintPayloadFields(
            field_name="updateSessionBlueprint", arguments=cleared_arguments
        )

    @classmethod
    def update_session_participations(
        cls, attributes: list[SessionParticipationAttributes]
    ) -> UpdateSessionParticipationsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "[SessionParticipationAttributes!]!",
                "value": attributes,
            }
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateSessionParticipationsPayloadFields(
            field_name="updateSessionParticipations", arguments=cleared_arguments
        )

    @classmethod
    def update_session_positions(
        cls, id: str, attributes: SessionPositionsAttributes
    ) -> UpdateSessionPositionsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "attributes": {"type": "SessionPositionsAttributes!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateSessionPositionsPayloadFields(
            field_name="updateSessionPositions", arguments=cleared_arguments
        )

    @classmethod
    def update_session_segment(
        cls, id: str, *, patch: Optional[SegmentPatch] = None
    ) -> UpdateSegmentPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "patch": {"type": "SegmentPatch", "value": patch},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateSegmentPayloadFields(
            field_name="updateSessionSegment", arguments=cleared_arguments
        )

    @classmethod
    def update_session_segments(
        cls, patches: list[SegmentPatch]
    ) -> UpdateSegmentsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "patches": {"type": "[SegmentPatch!]!", "value": patches}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateSegmentsPayloadFields(
            field_name="updateSessionSegments", arguments=cleared_arguments
        )

    @classmethod
    def update_session_tag_definition(
        cls, id: str, attributes: SessionTagDefinitionAttributes
    ) -> UpdateSessionTagDefinitionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "attributes": {
                "type": "SessionTagDefinitionAttributes!",
                "value": attributes,
            },
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateSessionTagDefinitionPayloadFields(
            field_name="updateSessionTagDefinition", arguments=cleared_arguments
        )

    @classmethod
    def update_staff_billing(
        cls, attributes: list[UpdateStaffBillingAttributes]
    ) -> UpdateStaffBillingPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "[UpdateStaffBillingAttributes!]!",
                "value": attributes,
            }
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateStaffBillingPayloadFields(
            field_name="updateStaffBilling", arguments=cleared_arguments
        )

    @classmethod
    def update_survey(
        cls, id: str, attributes: SurveyAttributes
    ) -> UpdateSurveyPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "attributes": {"type": "SurveyAttributes!", "value": attributes},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateSurveyPayloadFields(
            field_name="updateSurvey", arguments=cleared_arguments
        )

    @classmethod
    def update_survey_timer_trigger(
        cls, survey_timer_trigger_id: str, attributes: SurveyTimerTriggerAttributes
    ) -> UpdateSurveyTimerTriggerPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "surveyTimerTriggerId": {"type": "ID!", "value": survey_timer_trigger_id},
            "attributes": {
                "type": "SurveyTimerTriggerAttributes!",
                "value": attributes,
            },
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateSurveyTimerTriggerPayloadFields(
            field_name="updateSurveyTimerTrigger", arguments=cleared_arguments
        )

    @classmethod
    def update_tag_definition(
        cls, attributes: TagDefinitionAttributes, id: str
    ) -> UpdateTagDefinitionPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "TagDefinitionAttributes!", "value": attributes},
            "id": {"type": "ID!", "value": id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateTagDefinitionPayloadFields(
            field_name="updateTagDefinition", arguments=cleared_arguments
        )

    @classmethod
    def update_user_preferences(
        cls, attributes: UpdateUserPreferencesAttributes
    ) -> UpdateUserPreferencesPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "UpdateUserPreferencesAttributes!",
                "value": attributes,
            }
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpdateUserPreferencesPayloadFields(
            field_name="updateUserPreferences", arguments=cleared_arguments
        )

    @classmethod
    def upsert_chat_club_context(
        cls, attributes: ClubContextAttributes, club_id: str
    ) -> UpsertChatClubContextPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "ClubContextAttributes!", "value": attributes},
            "clubId": {"type": "ID!", "value": club_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpsertChatClubContextPayloadFields(
            field_name="upsertChatClubContext", arguments=cleared_arguments
        )

    @classmethod
    def upsert_chat_coach_context(
        cls, attributes: CoachContextAttributesInput
    ) -> UpsertChatCoachContextPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "CoachContextAttributesInput!", "value": attributes}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpsertChatCoachContextPayloadFields(
            field_name="upsertChatCoachContext", arguments=cleared_arguments
        )

    @classmethod
    def upsert_data_recordings(
        cls, attributes: list[UpsertDataRecordingsAttributes], session_id: str
    ) -> UpsertDataRecordingsPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {
                "type": "[UpsertDataRecordingsAttributes!]!",
                "value": attributes,
            },
            "sessionId": {"type": "ID!", "value": session_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpsertDataRecordingsPayloadFields(
            field_name="upsertDataRecordings", arguments=cleared_arguments
        )

    @classmethod
    def upsert_session_plan(
        cls,
        attributes: SessionPlanAttributesInput,
        club_id: str,
        *,
        session_plan_id: Optional[str] = None,
    ) -> UpsertSessionPlanPayloadFields:
        arguments: dict[str, dict[str, Any]] = {
            "attributes": {"type": "SessionPlanAttributesInput!", "value": attributes},
            "clubId": {"type": "ID!", "value": club_id},
            "sessionPlanId": {"type": "ID", "value": session_plan_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UpsertSessionPlanPayloadFields(
            field_name="upsertSessionPlan", arguments=cleared_arguments
        )
