# Generated by ariadne-codegen
# Source: schema.graphql

from enum import Enum


class ActiveFirmwareBoardName(str, Enum):
    """Board versions that are not archived, for use when selecting from the current range"""

    playerdata_anchor_v6_0_3 = "playerdata_anchor_v6_0_3"
    playerdata_ball_v1_0_2 = "playerdata_ball_v1_0_2"
    playerdata_ball_v1_1_0 = "playerdata_ball_v1_1_0"
    playerdata_edge_v2_0_8 = "playerdata_edge_v2_0_8"
    playerdata_edge_v2_1_1 = "playerdata_edge_v2_1_1"
    playerdata_edge_v3_1_0 = "playerdata_edge_v3_1_0"
    playerdata_gateway_v2_0_3_nrf5340_cpuapp = (
        "playerdata_gateway_v2_0_3_nrf5340_cpuapp"
    )


class AggFuncEnum(str, Enum):
    """The different aggregation functions"""

    avg = "avg"
    avgByAthlete = "avgByAthlete"
    avgByParticipation = "avgByParticipation"
    avgBySession = "avgBySession"
    max = "max"
    sum = "sum"


class AppAuthenticationFlow(str, Enum):
    ATHLETE_DASHBOARD = "ATHLETE_DASHBOARD"
    "Person is directed to Athlete Dashboard"
    CLUB_SETUP = "CLUB_SETUP"
    "Person needs to set up their club"
    CURRENT_CLUB = "CURRENT_CLUB"
    "Person has club, decide route on client side"
    CURRENT_ORGANISATION = "CURRENT_ORGANISATION"
    "Person has organisation, decide route on client side"
    DETAILS = "DETAILS"
    "Person without DOB or gender"
    EDGE_ASSIGNMENT = "EDGE_ASSIGNMENT"
    "Person has an Edge that can be scanned"
    NO_CLUB = "NO_CLUB"
    "Person has no club or individual Athlete"
    PRIVACY_POLICY_ACCEPTANCE = "PRIVACY_POLICY_ACCEPTANCE"
    "Person needs to accept a new privacy policy"
    SELECT_CLUB = "SELECT_CLUB"
    "Can select from a list of clubs"
    UPDATE_APP = "UPDATE_APP"
    "Person needs to update app to latest version"


class AppMessageTypeEnum(str, Enum):
    AccountSuspended = "AccountSuspended"
    AccountUnpaid = "AccountUnpaid"
    DataReady = "DataReady"
    FirmwareUpdateAvailable = "FirmwareUpdateAvailable"
    GatewayFirmwareUpdateAvailable = "GatewayFirmwareUpdateAvailable"
    LegacySurveyDistributed = "LegacySurveyDistributed"
    NewPersonalBest = "NewPersonalBest"
    SessionBlueprintSessionCreationFailed = "SessionBlueprintSessionCreationFailed"
    SessionBlueprintSessionCreationSkippedAthletes = (
        "SessionBlueprintSessionCreationSkippedAthletes"
    )
    SessionBlueprintSessionCreationSkippedGateways = (
        "SessionBlueprintSessionCreationSkippedGateways"
    )
    SurveyCompleted = "SurveyCompleted"
    SurveyReminder = "SurveyReminder"


class BulkActionEnum(str, Enum):
    """Actions supported by createBulkAction"""

    approve = "approve"
    "Approve records (e.g. promote pending members to athletes or staff)"
    archive = "archive"
    "Archive records in their source club"
    copy = "copy"
    "Copy records from a source club into one or more target clubs"
    delete = "delete"
    "Delete records in their source club"
    grant = "grant"
    "Grant a role to records (e.g. grant org_admin to people)"
    reject = "reject"
    "Reject records (e.g. remove pending members without approval)"
    reset = "reset"
    "Reset records to default values"
    revoke = "revoke"
    "Revoke a role from records (e.g. revoke org_admin from people)"
    unarchive = "unarchive"
    "Restore archived records in their source club"


class BulkActionableTypeEnum(str, Enum):
    """Entity types supported by createBulkAction"""

    Athlete = "Athlete"
    "Perform bulk action on athletes"
    AthleteGroup = "AthleteGroup"
    "Perform bulk action on athlete groups"
    Club = "Club"
    "Perform bulk action on clubs"
    ClubMetricZones = "ClubMetricZones"
    "Perform bulk action on club metric zones"
    PendingMember = "PendingMember"
    "Perform bulk action on pending members"
    Person = "Person"
    "Perform bulk action on people"
    Pitch = "Pitch"
    "Perform bulk action on pitches"
    Staff = "Staff"
    "Perform bulk action on staff"
    Survey = "Survey"
    "Perform bulk action on surveys"
    Tag = "Tag"
    "Perform bulk action on tags"


class BulkOperationRowStatusEnum(str, Enum):
    """Per-row result status for a bulk operation"""

    archived = "archived"
    "Row archived"
    created = "created"
    "Row created"
    deleted = "deleted"
    "Row deleted"
    error = "error"
    "Row error"
    overwritten = "overwritten"
    "Row overwritten"
    reset = "reset"
    "Row reset"
    skipped = "skipped"
    "Row skipped"
    succeeded = "succeeded"
    "Row succeeded"
    unarchived = "unarchived"
    "Row unarchived"


class BulkOperationStatusEnum(str, Enum):
    """Lifecycle status of a bulk operation record"""

    Failed = "Failed"
    "Bulk operation is failed"
    Pending = "Pending"
    "Bulk operation is pending"
    Processing = "Processing"
    "Bulk operation is processing"
    Succeeded = "Succeeded"
    "Bulk operation is succeeded"


class CallSiteEnum(str, Enum):
    """The page or feature from which the chat was initiated"""

    FLEXIBLE_REPORT_INDEX = "FLEXIBLE_REPORT_INDEX"
    "Chat opened from the flexible reporting page"


class ChartDataTypeEnum(str, Enum):
    """data type for a column, required by AG Grid when creating charts"""

    category = "category"
    excluded = "excluded"
    series = "series"
    time = "time"


class ChartTypeEnum(str, Enum):
    """The different chart types we support"""

    bar = "bar"
    boxPlot = "boxPlot"
    column = "column"
    columnLineCombo = "columnLineCombo"
    customCombo = "customCombo"
    line = "line"
    pie = "pie"
    radarLine = "radarLine"
    scatter = "scatter"
    stackedBar = "stackedBar"
    stackedColumn = "stackedColumn"
    table = "table"


class ClipTeam(str, Enum):
    """The team associated with a clip"""

    Opponent = "Opponent"
    OwnTeam = "OwnTeam"


class ClubSport(str, Enum):
    american_football = "american_football"
    association_football = "association_football"
    association_football_referees = "association_football_referees"
    baseball = "baseball"
    basketball = "basketball"
    basketball_lps = "basketball_lps"
    cricket = "cricket"
    gaelic_football = "gaelic_football"
    hockey = "hockey"
    hurling = "hurling"
    mens_lacrosse = "mens_lacrosse"
    other = "other"
    polo = "polo"
    rugby = "rugby"
    rugby_league = "rugby_league"
    shinty = "shinty"
    volleyball = "volleyball"
    womens_lacrosse = "womens_lacrosse"


class ConfiguredMetricListTypeEnum(str, Enum):
    """Configured metric list type."""

    leaderboard = "leaderboard"
    "Leaderboard"


class CreatorTypeEnum(str, Enum):
    """The type of polymorphic creator"""

    Athlete = "Athlete"
    Staff = "Staff"


class CustomMaxMetricEnum(str, Enum):
    """Available custom max metric types for athletes"""

    ACCELERATION = "ACCELERATION"
    "Maximum acceleration in m/s²"
    DECELERATION = "DECELERATION"
    "Maximum deceleration in m/s²"
    HEART_RATE = "HEART_RATE"
    "Maximum heart rate in BPM"
    SPEED = "SPEED"
    "Top speed in km/h"


class DatafileFormat(str, Enum):
    json = "json"
    raw = "raw"
    v3 = "v3"
    v4 = "v4"


class DatasetStatusEnum(str, Enum):
    """Status of a dataset"""

    Completed = "Completed"
    Failed = "Failed"
    Generating = "Generating"


class DecryptionArea(str, Enum):
    EdgeName = "EdgeName"
    EnableDFU = "EnableDFU"
    HeartrateAssociationService = "HeartrateAssociationService"
    MeshInit = "MeshInit"


class DetectedMatchEventState(str, Enum):
    confirmed = "confirmed"
    dismissed = "dismissed"
    pending = "pending"


class DeviceOwnerType(str, Enum):
    """The type of owner for a device"""

    Organisation = "Organisation"
    Person = "Person"


class DeviceSyncTypeEnum(str, Enum):
    """The different device types that can be synced"""

    ball = "ball"
    edge = "edge"


class DeviceTypeEnum(str, Enum):
    """The different harware devices"""

    Anchor = "Anchor"
    Ball = "Ball"
    Edge = "Edge"
    Gateway = "Gateway"


class DiagnosticWarningErrorTypeEnum(str, Enum):
    """The type of diagnostic error"""

    BATTERY_DEPLETION = "BATTERY_DEPLETION"
    DATA_OUTSIDE_TIME_WINDOW = "DATA_OUTSIDE_TIME_WINDOW"
    DATA_OVERWRITTEN = "DATA_OVERWRITTEN"
    GPS_QUALITY = "GPS_QUALITY"
    NO_GPS_DATA = "NO_GPS_DATA"
    PITCH_LOCATION_ERROR = "PITCH_LOCATION_ERROR"
    UNIT_NOT_WORN = "UNIT_NOT_WORN"
    UNIT_SWITCHED_OFF = "UNIT_SWITCHED_OFF"


class DisplayUnitEnum(str, Enum):
    """The display unit of the metric"""

    BPM = "BPM"
    "Beats per minute"
    CM = "CM"
    "Centimeters"
    HOUR = "HOUR"
    "Hours"
    KM = "KM"
    "Kilometers"
    KPH = "KPH"
    "Kilometers per hour"
    M = "M"
    "Meters"
    MIN = "MIN"
    "Minutes"
    MMSS = "MMSS"
    "Minutes:Seconds"
    MPS = "MPS"
    "Meters per second"
    PERCENT = "PERCENT"
    "Percentage"
    SEC = "SEC"
    "Seconds"
    UNITLESS = "UNITLESS"
    "Unitless"


class EdgeOwnerType(str, Enum):
    """The type of owner for a device"""

    Organisation = "Organisation"
    Person = "Person"


class FeatureNameEnum(str, Enum):
    """An enum of all the features that can be enabled/disabled"""

    activestorage_seaweedfs_cache = "activestorage_seaweedfs_cache"
    "When enabled, ActiveStorage uses SeaweedFS as an in-cluster read-through cache:\nuploads/deletes are duplicated from GCS to SeaweedFS, and reads (download,\nexist?, internal_url) prefer SeaweedFS and fall back to GCS. When disabled,\nall storage operations go straight to GCS."
    allow_font_scaling = "allow_font_scaling"
    "Enables scaling fonts for accessibility"
    anonymise_data_pipeline_enabled = "anonymise_data_pipeline_enabled"
    "Enables the anonymisation of session data on data recording addition"
    auto_gateway_assignment = "auto_gateway_assignment"
    "Enables processing of gateway assignments received from the gateway assignment pipeline"
    auto_pitch_detection = "auto_pitch_detection"
    "Enables auto pitch detection (deprecated)"
    bad_data_clipping = "bad_data_clipping"
    "Enables the bad data clipping feature in the web application"
    ball_metrics = "ball_metrics"
    "Enables ball metrics"
    browser_report_gen = "browser_report_gen"
    "Enable report generation in the browser"
    bt_hr_sensor_pairing = "bt_hr_sensor_pairing"
    "Enables setting up an edge to pair with a HR sensor"
    camera_upload = "camera_upload"
    "Enables camera upload from app"
    club_onboarding_flow = "club_onboarding_flow"
    "**Deprecated** Enables the new club onboarding flow"
    club_setup_flow = "club_setup_flow"
    "Enables the new club setup flow"
    coachmate_in_flexible_reports = "coachmate_in_flexible_reports"
    "Enables coachmate being used within flexible reporting"
    configurable_comparison = "configurable_comparison"
    "Enables configurable metric comparisons"
    configurable_metrics = "configurable_metrics"
    "*Deprecated* Enables scoped metric display by club"
    csv_exports = "csv_exports"
    "Enable survey exports in CSV format"
    custom_csv = "custom_csv"
    "Enables csv reporting options"
    custom_survey_questions = "custom_survey_questions"
    "Enables custom survey questions"
    data_recording_preprocessing = "data_recording_preprocessing"
    "Enables the data recording preprocessing pipeline (transforms raw sensor data\nindependently of session-level analysis)"
    device_management_v2 = "device_management_v2"
    "Enables the unified device management screen (edges, balls, gateways, anchors in one place)"
    edge_scheduled_wakeup = "edge_scheduled_wakeup"
    "Enables scheduled wakeup of edge devices"
    enhanced_settings = "enhanced_settings"
    "Enables the enhanced settings screens (Manage Athletes, Manage Staff, EDGE Assignment) on mobile"
    flexible_report_templates = "flexible_report_templates"
    "Select from templates while creating a new Flexible Report"
    flexible_reporting_v2 = "flexible_reporting_v2"
    "Enables flexible reporting v2"
    flexible_reports_split_duplicate_segments = (
        "flexible_reports_split_duplicate_segments"
    )
    'In flexible reports, suffixes duplicate segment titles by position (e.g. "Indy" / "Indy 2")\nso that multiple independent segments of the same type appear as separate chart columns'
    heartrate_data = "heartrate_data"
    "*Deprecated by Configurable Metrics*"
    hubspot_integration = "hubspot_integration"
    "Enables a variety of integrations with the hubspot API"
    imu_motion_estimation = "imu_motion_estimation"
    "Enables motion estimation from IMU sensor data"
    individual_speed_zones = "individual_speed_zones"
    "Enables the individual speed zones feature"
    localized_terms = "localized_terms"
    "Enables US / GB specific sports terms (e.g. match -> game)"
    match_session_parts_processing_v2 = "match_session_parts_processing_v2"
    "Enables new match session part processing"
    notification_enhancements = "notification_enhancements"
    "Enables the reworked notifications modal"
    organisation_admin_panel = "organisation_admin_panel"
    "Enables the organisation Admin Panel UI for the current organisation.\nRolled out per-organisation via the rollout admin tooling."
    pitches_on_sessions = "pitches_on_sessions"
    "Enables reading & writing pitches from Sessions::Session"
    processing_diagnostics = "processing_diagnostics"
    "Enables processing diagnostics"
    recruitment_dashboard = "recruitment_dashboard"
    "Enables access to the recruitment dashboard via SSO"
    report_improvements = "report_improvements"
    "Enables the report improvements feature"
    segment_naming_rule_relaxation = "segment_naming_rule_relaxation"
    "Enables the relaxation of segment naming rules to allow for more characters"
    session_automation = "session_automation"
    "Enables detected sessions v2"
    session_creation_loop = "session_creation_loop"
    "Enables the AI powered session creation loop"
    session_device_checks = "session_device_checks"
    "Shows the device battery checker page in a session"
    session_group_filter = "session_group_filter"
    "Enables filtering session overview by athlete groups"
    session_quick_actions = "session_quick_actions"
    "Enables quick actions on sessions"
    session_targets = "session_targets"
    "Enables setting targets on sessions"
    survey_archival = "survey_archival"
    "Enables archival of surveys"
    sync_only_recent_edges = "sync_only_recent_edges"
    "Filters edge sync list to only show edges from a specific session"
    tablet_session_view = "tablet_session_view"
    "Enables the redesigned tablet session screen with the table-style athlete metrics overview"
    tactical_map_speed = "tactical_map_speed"
    "Enables speed graphs on tactical maps"
    tactical_video_playback = "tactical_video_playback"
    "Enables the tactical video playback feature"
    training_plan_import = "training_plan_import"
    "Enables coaches to upload PDF training plans that are parsed into sessions and segments"
    use_competitor_s_metrics = "use_competitor_s_metrics"
    "Enables using competitor S acceleration/deceleration metrics"
    warmup_match_session = "warmup_match_session"
    "Enables warmup match session definitions"
    web_segments = "web_segments"
    "Enables segment creation on the web"
    zone_management_v2 = "zone_management_v2"
    "Enables the 2026 redesign of individual and club zone management"


class FirmwareBoardName(str, Enum):
    playerdata_anchor_v3_0_0 = "playerdata_anchor_v3_0_0"
    playerdata_anchor_v5_0_0 = "playerdata_anchor_v5_0_0"
    playerdata_anchor_v6_0_3 = "playerdata_anchor_v6_0_3"
    playerdata_ball_v1_0_2 = "playerdata_ball_v1_0_2"
    playerdata_ball_v1_1_0 = "playerdata_ball_v1_1_0"
    playerdata_edge_v2_0_8 = "playerdata_edge_v2_0_8"
    playerdata_edge_v2_0_81 = "playerdata_edge_v2_0_81"
    playerdata_edge_v2_0_9 = "playerdata_edge_v2_0_9"
    playerdata_edge_v2_1_1 = "playerdata_edge_v2_1_1"
    playerdata_edge_v2_2_0 = "playerdata_edge_v2_2_0"
    playerdata_edge_v3_0_5 = "playerdata_edge_v3_0_5"
    playerdata_edge_v3_1_0 = "playerdata_edge_v3_1_0"
    playerdata_gateway_v1_0_0 = "playerdata_gateway_v1_0_0"
    playerdata_gateway_v2_0_2_nrf5340_cpuapp = (
        "playerdata_gateway_v2_0_2_nrf5340_cpuapp"
    )
    playerdata_gateway_v2_0_3_nrf5340_cpuapp = (
        "playerdata_gateway_v2_0_3_nrf5340_cpuapp"
    )


class FirmwareBuildProfile(str, Enum):
    debug = "debug"
    release = "release"


class FirmwareFeatureVariant(str, Enum):
    datafile_v4 = "datafile_v4"
    fixed = "fixed"
    imu_recording = "imu_recording"
    no_stillness = "no_stillness"
    normal = "normal"


class FirmwareProject(str, Enum):
    anchor = "anchor"
    anchor_factory_test = "anchor_factory_test"
    edge = "edge"
    edge_factory_test = "edge_factory_test"
    gateway_v2 = "gateway_v2"


class FirmwareVariant(str, Enum):
    debug = "debug"
    release = "release"


class ImageSizeEnum(str, Enum):
    """Standard square image sizes for profile pictures"""

    EXTRA_LARGE = "EXTRA_LARGE"
    "640x640"
    LARGE = "LARGE"
    "320x320"
    MEDIUM = "MEDIUM"
    "160x160"
    SMALL = "SMALL"
    "80x80"


class Intensity(str, Enum):
    """Predicted session intensity levels"""

    high = "high"
    low = "low"
    medium = "medium"


class LabelPositionEnum(str, Enum):
    """Supported overlay label positions"""

    bottom = "bottom"
    bottom_left = "bottom_left"
    bottom_right = "bottom_right"
    inside = "inside"
    inside_left = "inside_left"
    inside_right = "inside_right"
    none = "none"
    top = "top"
    top_left = "top_left"
    top_right = "top_right"


class MatchEventClassEnum(str, Enum):
    """Classes of match event"""

    OnPitchEvent = "OnPitchEvent"
    PitchEntryEvent = "PitchEntryEvent"
    PitchExitEvent = "PitchExitEvent"


class MatchEventTeam(str, Enum):
    both_teams = "both_teams"
    opposing_team = "opposing_team"
    our_team = "our_team"


class MatchSessionResult(str, Enum):
    draw = "draw"
    loss = "loss"
    win = "win"


class OperatingMode(str, Enum):
    BatteryCritical = "BatteryCritical"
    ChargeMode = "ChargeMode"
    DataCapture = "DataCapture"
    DataCaptureIndoor = "DataCaptureIndoor"
    DataCaptureOutdoor = "DataCaptureOutdoor"
    DataTransfer = "DataTransfer"
    Error = "Error"
    FirmwareUpdate = "FirmwareUpdate"
    HrPeripheralPairing = "HrPeripheralPairing"
    Initialisation = "Initialisation"
    Powerdown = "Powerdown"


class OrderDirectionEnum(str, Enum):
    asc = "asc"
    desc = "desc"


class OrganisationPersonStatusEnum(str, Enum):
    """Whether a person is active or archived within an organisation"""

    ACTIVE = "ACTIVE"
    "Has at least one active staff record or organisation membership"
    ARCHIVED = "ARCHIVED"
    "All staff records and organisation memberships are archived"


class OwnerEnum(str, Enum):
    Club = "Club"
    Person = "Person"


class ParticipantDataExportFormatEnum(str, Enum):
    """Output format for a participant data export"""

    JSON = "JSON"
    "The JSON format"


class ParticipantDataExportStatusEnum(str, Enum):
    """Status of a participant data export"""

    Completed = "Completed"
    Failed = "Failed"
    Generating = "Generating"


class PathmapPathType(str, Enum):
    high_intensity = "high_intensity"
    "high_intensity"
    sprint = "sprint"
    "sprint"


class PendingMemberTypeEnum(str, Enum):
    """Role a pending member will hold once approved"""

    ATHLETE = "ATHLETE"
    "Pending athlete"
    STAFF = "STAFF"
    "Pending staff"


class PermissionAction(str, Enum):
    Create = "Create"
    Destroy = "Destroy"
    Edit = "Edit"
    Export = "Export"
    Index = "Index"
    New = "New"
    Show = "Show"
    Update = "Update"


class PermissionEnum(str, Enum):
    """An enum of all available RBAC permissions"""

    approve_pending_members = "approve_pending_members"
    create_athlete_groups = "create_athlete_groups"
    create_athletes = "create_athletes"
    create_members = "create_members"
    create_pitches = "create_pitches"
    create_reports = "create_reports"
    create_sessions = "create_sessions"
    create_staff = "create_staff"
    create_surveys = "create_surveys"
    create_tags = "create_tags"
    destroy_reports = "destroy_reports"
    force_retrigger_processing = "force_retrigger_processing"
    manage_oauth_applications = "manage_oauth_applications"
    manage_roles = "manage_roles"
    manage_video_storage_limits = "manage_video_storage_limits"
    run_maintenance_tasks = "run_maintenance_tasks"
    unlock_logins = "unlock_logins"
    update_athlete_groups = "update_athlete_groups"
    update_athletes = "update_athletes"
    update_clubs = "update_clubs"
    update_members = "update_members"
    update_organisations = "update_organisations"
    update_pitches = "update_pitches"
    update_reports = "update_reports"
    update_sessions = "update_sessions"
    update_settings = "update_settings"
    update_staff = "update_staff"
    update_surveys = "update_surveys"
    update_tags = "update_tags"
    view_all_organisations = "view_all_organisations"
    view_athlete_groups = "view_athlete_groups"
    view_athletes = "view_athletes"
    view_clubs = "view_clubs"
    view_members = "view_members"
    view_pending_members = "view_pending_members"
    view_pitches = "view_pitches"
    view_reports = "view_reports"
    view_sessions = "view_sessions"
    view_settings = "view_settings"
    view_staff = "view_staff"
    view_surveys = "view_surveys"
    view_tags = "view_tags"


class PermissionSubject(str, Enum):
    Athlete = "Athlete"
    ClubSettings = "ClubSettings"
    Organisation = "Organisation"
    PendingMember = "PendingMember"
    Person = "Person"
    Pitch = "Pitch"
    Report = "Report"
    Session = "Session"
    SessionTagDefinition = "SessionTagDefinition"
    Survey = "Survey"
    SurveyDistribution = "SurveyDistribution"
    SurveyQuestion = "SurveyQuestion"
    SurveyTimerTrigger = "SurveyTimerTrigger"


class Platform(str, Enum):
    ANDROID = "ANDROID"
    "A device running Android"
    IOS = "IOS"
    "A device running iOS"
    WEB = "WEB"
    "Running in a web browser"


class PreprocessingOutputFileTypeEnum(str, Enum):
    """Data type of a preprocessing output file"""

    GPS = "GPS"
    HEARTRATE = "HEARTRATE"
    IMU = "IMU"
    IMU_ACCELERATION = "IMU_ACCELERATION"
    UWB = "UWB"


class ProcessingWarning(str, Enum):
    ANCHOR_LOCALISATION_FAILED = "ANCHOR_LOCALISATION_FAILED"
    "The anchor auto localisation process failed"
    FILTERED_BY_PITCH_BOUNDS = "FILTERED_BY_PITCH_BOUNDS"
    "Provided data was (almost) entirely filtered by pitch bounds"
    FILTERED_BY_SATELLITE_COUNT = "FILTERED_BY_SATELLITE_COUNT"
    "Provided data predominantly below satellite count threshold"
    FILTERED_BY_TIME = "FILTERED_BY_TIME"
    "Provided data was (almost) entirely filtered out by time bounds"
    INSUFFICIENT_LPS_DATA_TO_LOCALISE = "INSUFFICIENT_LPS_DATA_TO_LOCALISE"
    "There was insufficient LPS data to track the athletes position"
    LOW_DATA_POINTS = "LOW_DATA_POINTS"
    "Not enough high speed points to create a pitch from"
    NO_ACCELERATION_DATA = "NO_ACCELERATION_DATA"
    "There was no acceleration data in the provided file"
    NO_ANCHOR_DATA = "NO_ANCHOR_DATA"
    "There was no anchor data recorded"
    NO_DATA_FILE = "NO_DATA_FILE"
    "Session reprocessed without datafile"
    NO_DELTA_DATA = "NO_DELTA_DATA"
    "There was no delta data recorded"
    NO_EDGE_DATA = "NO_EDGE_DATA"
    "There was no data in the provided file"
    NO_GPS_DATA = "NO_GPS_DATA"
    "There was no GPS data in the provided file"
    NO_LPS_DATA = "NO_LPS_DATA"
    "There was no LPS data recorded"
    NO_PITCH_DETECTED = "NO_PITCH_DETECTED"
    "No pitch was detected for this session"
    NO_UWB_ANCHOR_POSITION_DATA = "NO_UWB_ANCHOR_POSITION_DATA"
    "(DEPRECATED) There was no UWB anchor position data in the provided file"
    NO_UWB_DATA = "NO_UWB_DATA"
    "(DEPRECATED) There was no UWB data in the provided file"
    NO_UWB_DELTA_TAG_DATA = "NO_UWB_DELTA_TAG_DATA"
    "(DEPRECATED) There was no UWB delta tag data in the provided file"
    NO_VALID_LOCALISATION_DATA = "NO_VALID_LOCALISATION_DATA"
    "Could not produce valid LPS tracking data"
    NO_VALID_LPS_DATA = "NO_VALID_LPS_DATA"
    "There was no valid LPS data recorded"
    PITCH_TOO_LARGE = "PITCH_TOO_LARGE"
    "The pitch created by pitch detection was initially too large (150m x 200m)\n            reflecting a high speed in a large area."
    PITCH_TOO_SMALL = "PITCH_TOO_SMALL"
    "The pitch created by pitch detection was initially too small (20m x 50m)\n            reflecting a high speed in a small area."
    UWB_HYBRID_SYSTEMS_NOT_SUPPORTED = "UWB_HYBRID_SYSTEMS_NOT_SUPPORTED"
    "(DEPRECATED) Fixed and floating anchors not supported yet"
    UWB_LOCALISATION_FAILED = "UWB_LOCALISATION_FAILED"
    "(DEPRECATED) The localisation process failed for the provided UWB data"


class ProfileRegistrationStatusEnum(str, Enum):
    """Registration status of an athlete or staff member"""

    INVITED = "INVITED"
    "Uploaded or invited but has not confirmed their account yet"
    REGISTERED = "REGISTERED"
    "Has a confirmed account"
    UNCLAIMED = "UNCLAIMED"
    "Has an account but has not been claimed yet"
    UNCONFIRMED = "UNCONFIRMED"
    "Has an account but has not confirmed it yet"


class QuickActionStateEnum(str, Enum):
    """Enum for quick action states"""

    AFTER_SESSION = "AFTER_SESSION"
    "Quick action state after session ends"
    BEFORE_SESSION = "BEFORE_SESSION"
    "Quick action state before session starts"
    MATCH_INSIDE_FINAL_SEGMENT = "MATCH_INSIDE_FINAL_SEGMENT"
    "Quick action state for match inside final segment"
    MATCH_INSIDE_NON_FINAL_SEGMENT = "MATCH_INSIDE_NON_FINAL_SEGMENT"
    "Quick action state for match inside non-final segment"
    MATCH_OUTSIDE_SEGMENT_WITH_FUTURE_SEGMENTS = (
        "MATCH_OUTSIDE_SEGMENT_WITH_FUTURE_SEGMENTS"
    )
    "Quick action state for matches to skip past breaks or other gaps between segments"
    TRAINING_INSIDE_SEGMENT_NEAR_SESSION_END = (
        "TRAINING_INSIDE_SEGMENT_NEAR_SESSION_END"
    )
    "Quick action state for training inside segment near session end (10 mins)"
    TRAINING_INSIDE_SEGMENT_NO_FUTURE_SEGMENTS = (
        "TRAINING_INSIDE_SEGMENT_NO_FUTURE_SEGMENTS"
    )
    "Quick action state for training inside segment with no future segments"
    TRAINING_INSIDE_SEGMENT_WITH_FUTURE_SEGMENTS = (
        "TRAINING_INSIDE_SEGMENT_WITH_FUTURE_SEGMENTS"
    )
    "Quick action state for training inside segment with future segments"
    TRAINING_OUTSIDE_SEGMENT_NEAR_SESSION_END = (
        "TRAINING_OUTSIDE_SEGMENT_NEAR_SESSION_END"
    )
    "Quick action state for training outside segment near session end (10 mins)"
    TRAINING_OUTSIDE_SEGMENT_NO_FUTURE_SEGMENTS = (
        "TRAINING_OUTSIDE_SEGMENT_NO_FUTURE_SEGMENTS"
    )
    "Quick action state for training outside segment with no segments"
    TRAINING_OUTSIDE_SEGMENT_WITH_FUTURE_SEGMENTS = (
        "TRAINING_OUTSIDE_SEGMENT_WITH_FUTURE_SEGMENTS"
    )
    "Quick action state for training outside segment with future segments"
    UNABLE_TO_DETERMINE = "UNABLE_TO_DETERMINE"
    "Failed to evaluate the correct quick action state for this session"


class RatingEnum(str, Enum):
    """The rating of a response or prediction"""

    negative = "negative"
    positive = "positive"


class RawDataFormatEnum(str, Enum):
    """Download format for a raw data type"""

    CSV = "CSV"
    "Comma-separated values, generated on demand from the pre-processed data"
    PARQUET = "PARQUET"
    "The raw pre-processed Apache Parquet file, served directly"


class RawDataPreparationStatusEnum(str, Enum):
    """Outcome of a prepareRawData mutation"""

    ALREADY_AVAILABLE = "ALREADY_AVAILABLE"
    "Raw data already covers the session window; nothing was started"
    IN_FLIGHT = "IN_FLIGHT"
    "A preparation run was already in flight; nothing was started"
    TRIGGERED = "TRIGGERED"
    "A new preparation run was started"
    UNAVAILABLE = "UNAVAILABLE"
    "Raw data could not be prepared (feature off, no device, or no recording)"


class RawDataStatusEnum(str, Enum):
    """Availability status of a raw data type for a session participation"""

    PROCESSING = "PROCESSING"
    "The data is being prepared; poll this field until it is READY"
    READY = "READY"
    "The raw data is available to download via the url field"
    UNAVAILABLE = "UNAVAILABLE"
    "No raw data is available and none can be produced for this data type"


class ReferenceOverlayTypeEnum(str, Enum):
    """Supported reference overlay types"""

    all_time_pb = "all_time_pb"
    match_pb = "match_pb"
    training_pb = "training_pb"


class ReportType(str, Enum):
    AthleteReport = "AthleteReport"
    GroupReport = "GroupReport"
    MultiSessionReport = "MultiSessionReport"
    SingleSessionReport = "SingleSessionReport"


class ReportTypeEnum(str, Enum):
    AthleteLoad = "AthleteLoad"
    MultiSession = "MultiSession"
    SingleSession = "SingleSession"


class ResponderEnum(str, Enum):
    bot = "bot"
    human = "human"
    system = "system"


class SeriesChartTypeEnum(str, Enum):
    """The different chart types we support for combo charts"""

    groupedColumn = "groupedColumn"
    line = "line"
    stackedColumn = "stackedColumn"


class SessionParticipationWarningCodes(str, Enum):
    """The codes for the warnings"""

    ANCHOR_LOCALISATION_FAILED = "ANCHOR_LOCALISATION_FAILED"
    "The anchor auto localisation process failed"
    EDGE_SYNC_REQUIRED = "EDGE_SYNC_REQUIRED"
    "Session has data syncs but one or more has no data file."
    FILTERED_BY_PITCH_BOUNDS = "FILTERED_BY_PITCH_BOUNDS"
    "Provided data was (almost) entirely filtered by pitch bounds"
    FILTERED_BY_SATELLITE_COUNT = "FILTERED_BY_SATELLITE_COUNT"
    "Provided data predominantly below satellite count threshold"
    FILTERED_BY_TIME = "FILTERED_BY_TIME"
    "Provided data was (almost) entirely filtered out by time bounds"
    FUTURE_SESSION = "FUTURE_SESSION"
    "Session start time is in the future."
    GATEWAY_ASSIGNABLE = "GATEWAY_ASSIGNABLE"
    "The session is in progress and a gateway can be assigned."
    GATEWAY_NOT_CONNECTED = "GATEWAY_NOT_CONNECTED"
    "The Gateway has not connected to the network."
    INSUFFICIENT_LPS_DATA_TO_LOCALISE = "INSUFFICIENT_LPS_DATA_TO_LOCALISE"
    "There was insufficient LPS data to track the athletes position"
    LIVE_INDOOR_SESSION = "LIVE_INDOOR_SESSION"
    "Live indoor session's are not supported."
    LIVE_SESSION_DATA_GAPS = "LIVE_SESSION_DATA_GAPS"
    "The session has gaps in data coverage that require edge sync."
    LOW_DATA_POINTS = "LOW_DATA_POINTS"
    "Not enough high speed points to create a pitch from"
    NO_ACCELERATION_DATA = "NO_ACCELERATION_DATA"
    "There was no acceleration data in the provided file"
    NO_ANCHOR_DATA = "NO_ANCHOR_DATA"
    "There was no anchor data recorded"
    NO_ATHLETES_ASSIGNED = "NO_ATHLETES_ASSIGNED"
    "Session has no session participations."
    NO_DATA_FILE = "NO_DATA_FILE"
    "Session reprocessed without datafile"
    NO_DELTA_DATA = "NO_DELTA_DATA"
    "There was no delta data recorded"
    NO_EDGES_ASSIGNED = "NO_EDGES_ASSIGNED"
    "Session has no data recordings."
    NO_EDGE_DATA = "NO_EDGE_DATA"
    "There was no data in the provided file"
    NO_GATEWAY_DATA = "NO_GATEWAY_DATA"
    "No data has been received from the Gateway."
    NO_GPS_DATA = "NO_GPS_DATA"
    "There was no GPS data in the provided file"
    NO_LPS_DATA = "NO_LPS_DATA"
    "There was no LPS data recorded"
    NO_PITCH_DETECTED = "NO_PITCH_DETECTED"
    "No pitch was detected for this session"
    NO_UWB_ANCHOR_POSITION_DATA = "NO_UWB_ANCHOR_POSITION_DATA"
    "(DEPRECATED) There was no UWB anchor position data in the provided file"
    NO_UWB_DATA = "NO_UWB_DATA"
    "(DEPRECATED) There was no UWB data in the provided file"
    NO_UWB_DELTA_TAG_DATA = "NO_UWB_DELTA_TAG_DATA"
    "(DEPRECATED) There was no UWB delta tag data in the provided file"
    NO_VALID_LOCALISATION_DATA = "NO_VALID_LOCALISATION_DATA"
    "Could not produce valid LPS tracking data"
    NO_VALID_LPS_DATA = "NO_VALID_LPS_DATA"
    "There was no valid LPS data recorded"
    PITCH_TOO_LARGE = "PITCH_TOO_LARGE"
    "The pitch created by pitch detection was initially too large (150m x 200m)\n            reflecting a high speed in a large area."
    PITCH_TOO_SMALL = "PITCH_TOO_SMALL"
    "The pitch created by pitch detection was initially too small (20m x 50m)\n            reflecting a high speed in a small area."
    UWB_HYBRID_SYSTEMS_NOT_SUPPORTED = "UWB_HYBRID_SYSTEMS_NOT_SUPPORTED"
    "(DEPRECATED) Fixed and floating anchors not supported yet"
    UWB_LOCALISATION_FAILED = "UWB_LOCALISATION_FAILED"
    "(DEPRECATED) The localisation process failed for the provided UWB data"


class SessionTypeEnum(str, Enum):
    """Enum for session type"""

    MatchSession = "MatchSession"
    "A session that is a match."
    TrainingSession = "TrainingSession"
    "A session that is a training."


class SessionWarningCodes(str, Enum):
    """The codes for the warnings"""

    EDGE_SYNC_REQUIRED = "EDGE_SYNC_REQUIRED"
    "Session has data syncs but one or more has no data file."
    FUTURE_SESSION = "FUTURE_SESSION"
    "Session start time is in the future."
    GATEWAY_ASSIGNABLE = "GATEWAY_ASSIGNABLE"
    "The session is in progress and a gateway can be assigned."
    GATEWAY_NOT_CONNECTED = "GATEWAY_NOT_CONNECTED"
    "The Gateway has not connected to the network."
    LIVE_INDOOR_SESSION = "LIVE_INDOOR_SESSION"
    "Live indoor session's are not supported."
    LIVE_SESSION_DATA_GAPS = "LIVE_SESSION_DATA_GAPS"
    "The session has gaps in data coverage that require edge sync."
    NO_ATHLETES_ASSIGNED = "NO_ATHLETES_ASSIGNED"
    "Session has no session participations."
    NO_EDGES_ASSIGNED = "NO_EDGES_ASSIGNED"
    "Session has no data recordings."
    NO_GATEWAY_DATA = "NO_GATEWAY_DATA"
    "No data has been received from the Gateway."


class SignupFlow(str, Enum):
    ALREADY_LINKED = "ALREADY_LINKED"
    "This user is already part of this club"
    INVALID_EMAIL = "INVALID_EMAIL"
    "The email address is invalid"
    LINK_TO_NEW_CLUB = "LINK_TO_NEW_CLUB"
    "This is an existing user but for a different club"
    NEW_CLAIMABLE_ATHLETE = "NEW_CLAIMABLE_ATHLETE"
    "This is a new user with a claimable athlete"
    NEW_USER = "NEW_USER"
    "This is a new user, not already part of a club"
    NO_EMAIL = "NO_EMAIL"
    "No email address has been provided yet"
    PENDING_MEMBER = "PENDING_MEMBER"
    "The application to join the club is waiting for a response from club staff"
    SIGN_IN_REQUIRED = "SIGN_IN_REQUIRED"
    "To continue, the person must sign in"


class SortField(str, Enum):
    avg_acceleration_events = "avg_acceleration_events"
    avg_deceleration_events = "avg_deceleration_events"
    avg_distance_m = "avg_distance_m"
    avg_high_intensity_distance_m = "avg_high_intensity_distance_m"
    avg_high_intensity_events = "avg_high_intensity_events"
    avg_high_intensity_run_distance_m = "avg_high_intensity_run_distance_m"
    avg_max_speed_kph = "avg_max_speed_kph"
    avg_metres_per_minute = "avg_metres_per_minute"
    avg_raw_max_speed_kph = "avg_raw_max_speed_kph"
    avg_sprint_distance_m = "avg_sprint_distance_m"
    avg_sprint_events = "avg_sprint_events"
    avg_total_high_intensity_distance_m = "avg_total_high_intensity_distance_m"
    avg_workload = "avg_workload"
    avg_workload_intensity = "avg_workload_intensity"
    avg_workload_volume = "avg_workload_volume"
    max_max_speed_kph = "max_max_speed_kph"
    max_metres_per_minute = "max_metres_per_minute"
    max_raw_max_speed_kph = "max_raw_max_speed_kph"
    max_total_distance_m = "max_total_distance_m"
    total_acceleration_events = "total_acceleration_events"
    total_deceleration_events = "total_deceleration_events"
    total_distance_m = "total_distance_m"
    total_high_intensity_distance_m = "total_high_intensity_distance_m"
    total_high_intensity_events = "total_high_intensity_events"
    total_high_intensity_run_distance_m = "total_high_intensity_run_distance_m"
    total_sprint_count = "total_sprint_count"
    total_sprint_distance_m = "total_sprint_distance_m"
    total_sprint_events = "total_sprint_events"


class StatOverlayTypeEnum(str, Enum):
    """Supported statistic overlay types"""

    average = "average"
    std_dev = "std_dev"


class StepEnum(str, Enum):
    """Available setup checklist step identifiers"""

    add_athletes = "add_athletes"
    add_staff = "add_staff"
    set_team_name = "set_team_name"
    setup_edges = "setup_edges"


class StepStatusEnum(str, Enum):
    """Possible statuses for a setup checklist step"""

    complete = "complete"
    "Complete"
    in_progress = "in_progress"
    "In progress"
    incomplete = "incomplete"
    "Incomplete"
    skipped = "skipped"
    "Skipped"


class StripeSubscriptionStatus(str, Enum):
    active = "active"
    cancelled = "cancelled"
    paused = "paused"
    unpaid = "unpaid"


class TaggableTypeEnum(str, Enum):
    """The types of model that tags can be applied to"""

    athlete = "athlete"
    match_session = "match_session"
    segment = "segment"
    segment_participation = "segment_participation"
    segment_participation_part = "segment_participation_part"
    session = "session"
    session_participation = "session_participation"
    training_session = "training_session"


class TaggerTypeEnum(str, Enum):
    Club = "Club"


class TargetAssignableTypeEnum(str, Enum):
    """The type of record a target definition can be assigned to"""

    ATHLETE = "ATHLETE"


class TargetStatusEnum(str, Enum):
    """The outcome status of a session target relative to the recorded value"""

    ABOVE = "ABOVE"
    BELOW = "BELOW"
    WITHIN = "WITHIN"


class TargetTargetableTypeEnum(str, Enum):
    """The type of record a session target can be attached to"""

    SESSION_PARTICIPATION = "SESSION_PARTICIPATION"


class TargetTypeEnum(str, Enum):
    """The kind of session target (absolute range or percentage range)"""

    ABSOLUTE_RANGE = "ABSOLUTE_RANGE"
    PERCENTAGE_RANGE = "PERCENTAGE_RANGE"


class TopicTypeEnum(str, Enum):
    """The type of entity a chat topic references"""

    FLEXIBLE_REPORT = "FLEXIBLE_REPORT"
    "A flexible report"


class TrainingPlanImportStatus(str, Enum):
    """Lifecycle status of a training plan import"""

    committed = "committed"
    failed = "failed"
    parsed = "parsed"
    parsing = "parsing"
    pending = "pending"


class UnitSystem(str, Enum):
    imperial = "imperial"
    imperial_yards_only = "imperial_yards_only"
    metres_per_second = "metres_per_second"
    metric = "metric"
